/**
 * 游戏注册表 —— 575 个游戏的元信息（大厅卡片 + 路由用）。
 *
 * 顺序即大厅展示顺序。这里是产品内容规模的唯一事实来源：
 * README、存档、成就、家长面板等统计都应从 GAMES/GAME_IDS 推导。
 * 颜色主题对应 style.css 的 CSS 变量。
 *
 * ⚠️ 本文件由 generic-admin 自动生成，请勿手改。
 *    数据源：generic-admin 后台的 kids-games-meta collection。
 *    编辑方法：在 generic-admin UI 改记录 → 跑 scripts/export-to-kids-games.mjs。
 */
import type { GameId, GameMeta } from "../types.ts";

export const GAMES: readonly GameMeta[] = [
  {
    id: "color-mixer",
    title: "色彩调配师",
    subtitle: "认识三原色，颜料真混合",
    icon: "🎨",
    theme: "--c-pink",
    age: "3-6 岁",
    tag: "认知·颜色",
  },
  {
    id: "shape-match",
    title: "形状配对",
    subtitle: "认识几何形状，配对小动物",
    icon: "🧩",
    theme: "--c-blue",
    age: "3-5 岁",
    tag: "认知·图形",
  },
  {
    id: "number-monster",
    title: "数字小怪兽",
    subtitle: "数数 1-20，喂饱小怪兽",
    icon: "🔢",
    theme: "--c-green",
    age: "4-6 岁",
    tag: "数学·计数",
  },
  {
    id: "letter-bee",
    title: "蜜蜂找字母",
    subtitle: "认字母首音，采对应花朵",
    icon: "🐝",
    theme: "--c-yellow",
    age: "4-6 岁",
    tag: "语言·字母",
  },
  {
    id: "memory-flip",
    title: "记忆翻翻乐",
    subtitle: "训练短时记忆，难度递增",
    icon: "🧠",
    theme: "--c-purple",
    age: "3-6 岁",
    tag: "逻辑·记忆",
  },
  {
    id: "music-stairs",
    title: "音乐楼梯",
    subtitle: "听音高节奏，弹奏小旋律",
    icon: "🎼",
    theme: "--c-orange",
    age: "3-6 岁",
    tag: "艺术·听觉",
  },
  {
    id: "maze-adventure",
    title: "走迷宫",
    subtitle: "空间推理，收集星星",
    icon: "🚗",
    theme: "--c-teal",
    age: "4-6 岁",
    tag: "逻辑·规划",
  },
  {
    id: "seek-find",
    title: "找一找",
    subtitle: "专注观察，发现隐藏物品",
    icon: "🎡",
    theme: "--c-red",
    age: "3-6 岁",
    tag: "专注·观察",
  },
  {
    id: "size-sort",
    title: "大小排队",
    subtitle: "比较大小，从小到大排队",
    icon: "📏",
    theme: "--c-orange",
    age: "3-5 岁",
    tag: "认知·比较",
  },
  {
    id: "jigsaw",
    title: "拼图小能手",
    subtitle: "还原打乱的图片",
    icon: "🧩",
    theme: "--c-purple",
    age: "3-6 岁",
    tag: "认知·空间",
  },
  {
    id: "pattern",
    title: "找规律",
    subtitle: "发现重复序列的下一个",
    icon: "🔁",
    theme: "--c-blue",
    age: "4-6 岁",
    tag: "逻辑·推理",
  },
  {
    id: "whack-mole",
    title: "打地鼠",
    subtitle: "快速反应，锻炼手眼协调",
    icon: "🔨",
    theme: "--c-brown",
    age: "3-6 岁",
    tag: "反应·协调",
  },
  {
    id: "doodle",
    title: "涂鸦画板",
    subtitle: "自由绘画，换颜色画笔",
    icon: "🖌️",
    theme: "--c-pink",
    age: "3-6 岁",
    tag: "创造·艺术",
  },
  {
    id: "weather",
    title: "天气小助手",
    subtitle: "认识天气与穿衣",
    icon: "🌤️",
    theme: "--c-teal",
    age: "3-6 岁",
    tag: "认知·生活",
  },
  {
    id: "clock",
    title: "小小时钟",
    subtitle: "认识整点与半点",
    icon: "🕐",
    theme: "--c-yellow",
    age: "5-6 岁",
    tag: "认知·时间",
  },
  {
    id: "animal-sound",
    title: "谁的声音",
    subtitle: "听声音猜动物",
    icon: "🐮",
    theme: "--c-green",
    age: "3-6 岁",
    tag: "认知·听觉",
  },
  {
    id: "color-sort",
    title: "颜色分家",
    subtitle: "按颜色把物品分类",
    icon: "🗂️",
    theme: "--c-cyan",
    age: "3-5 岁",
    tag: "认知·分类",
  },
  {
    id: "connect-dots",
    title: "连点成画",
    subtitle: "按数字顺序连线出图",
    icon: "✏️",
    theme: "--c-orange",
    age: "4-6 岁",
    tag: "认知·数序",
  },
  {
    id: "shadow-match",
    title: "影子朋友",
    subtitle: "把物品和它的影子配对",
    icon: "👥",
    theme: "--c-indigo",
    age: "3-6 岁",
    tag: "认知·观察",
  },
  {
    id: "tangram",
    title: "七巧板",
    subtitle: "用形状拼出图案",
    icon: "🔷",
    theme: "--c-purple",
    age: "4-6 岁",
    tag: "创造·空间",
  },
  {
    id: "farm-math",
    title: "小农场算术",
    subtitle: "数动物做加减法",
    icon: "🐔",
    theme: "--c-green",
    age: "5-6 岁",
    tag: "数学·运算",
  },
  {
    id: "balance",
    title: "天平称重",
    subtitle: "比较轻重，让天平平衡",
    icon: "⚖️",
    theme: "--c-teal",
    age: "4-6 岁",
    tag: "认知·比较",
  },
  {
    id: "robot-code",
    title: "小指令机器人",
    subtitle: "排指令让机器人到达终点",
    icon: "🤖",
    theme: "--c-blue",
    age: "5-6 岁",
    tag: "逻辑·编程",
  },
  {
    id: "dress-up",
    title: "换装搭配",
    subtitle: "给角色搭配服装",
    icon: "👕",
    theme: "--c-pink",
    age: "3-6 岁",
    tag: "创造·生活",
  },
  {
    id: "fruit-catch",
    title: "接水果",
    subtitle: "移动篮子接水果",
    icon: "🧺",
    theme: "--c-green",
    age: "3-6 岁",
    tag: "反应·协调",
  },
  {
    id: "link-match",
    title: "连连看",
    subtitle: "相同图案连线消除",
    icon: "🔗",
    theme: "--c-cyan",
    age: "4-6 岁",
    tag: "观察·配对",
  },
  {
    id: "feed-order",
    title: "喂养顺序",
    subtitle: "按指定顺序点动物",
    icon: "🍖",
    theme: "--c-orange",
    age: "3-6 岁",
    tag: "记忆·顺序",
  },
  {
    id: "pinyin",
    title: "拼音首字母",
    subtitle: "找对应拼音的字",
    icon: "🔤",
    theme: "--c-blue",
    age: "5-6 岁",
    tag: "语言·拼音",
  },
  {
    id: "antonym",
    title: "找反义词",
    subtitle: "把意思相反的词配对",
    icon: "⚖️",
    theme: "--c-indigo",
    age: "5-6 岁",
    tag: "语言·词汇",
  },
  {
    id: "sliding-puzzle",
    title: "数字华容道",
    subtitle: "滑动方块排顺序",
    icon: "🔢",
    theme: "--c-purple",
    age: "4-6 岁",
    tag: "逻辑·策略",
  },
  {
    id: "color-reaction",
    title: "颜色反应",
    subtitle: "听颜色名点对应色",
    icon: "🌈",
    theme: "--c-pink",
    age: "3-6 岁",
    tag: "反应·认知",
  },
  {
    id: "equation",
    title: "等式填空",
    subtitle: "填数字让等式成立",
    icon: "➗",
    theme: "--c-teal",
    age: "5-6 岁",
    tag: "数学·运算",
  },
  {
    id: "spot-diff",
    title: "找不同",
    subtitle: "找出两图的不同",
    icon: "🔍",
    theme: "--c-red",
    age: "4-6 岁",
    tag: "专注·观察",
  },
  {
    id: "tidy-up",
    title: "收拾房间",
    subtitle: "把物品放回原位",
    icon: "🧹",
    theme: "--c-brown",
    age: "3-6 岁",
    tag: "生活·分类",
  },
  {
    id: "mini-sudoku",
    title: "迷你数独",
    subtitle: "填不重复的图案",
    icon: "🔲",
    theme: "--c-indigo",
    age: "5-6 岁",
    tag: "逻辑·推理",
  },
  {
    id: "pipe-connect",
    title: "接水管",
    subtitle: "旋转管道连通水流",
    icon: "🚰",
    theme: "--c-cyan",
    age: "4-6 岁",
    tag: "逻辑·空间",
  },
  {
    id: "weight-sort",
    title: "称重排序",
    subtitle: "按轻重给动物排队",
    icon: "🐘",
    theme: "--c-brown",
    age: "4-6 岁",
    tag: "认知·比较",
  },
  {
    id: "catch-star",
    title: "接星星",
    subtitle: "限时收集掉落星星",
    icon: "⭐",
    theme: "--c-yellow",
    age: "3-6 岁",
    tag: "反应·协调",
  },
  {
    id: "draw-along",
    title: "照着画",
    subtitle: "沿虚线临摹图形",
    icon: "✒️",
    theme: "--c-purple",
    age: "3-6 岁",
    tag: "创造·精细",
  },
  {
    id: "emotion",
    title: "表情配对",
    subtitle: "情境配上对应情绪",
    icon: "😀",
    theme: "--c-orange",
    age: "3-6 岁",
    tag: "社交·情商",
  },
  {
    id: "direction",
    title: "方向辨别",
    subtitle: "分清左右上下",
    icon: "🧭",
    theme: "--c-blue",
    age: "4-6 岁",
    tag: "认知·空间",
  },
  {
    id: "length",
    title: "比长短",
    subtitle: "比较物品的长短",
    icon: "📏",
    theme: "--c-teal",
    age: "3-5 岁",
    tag: "认知·比较",
  },
  {
    id: "more-less",
    title: "多少比较",
    subtitle: "比较两组数量多少",
    icon: "⚖️",
    theme: "--c-green",
    age: "3-5 岁",
    tag: "数学·比较",
  },
  {
    id: "symmetry",
    title: "对称补全",
    subtitle: "补全对称的另一半",
    icon: "🦋",
    theme: "--c-pink",
    age: "4-6 岁",
    tag: "认知·空间",
  },
  {
    id: "rhythm",
    title: "节奏模仿",
    subtitle: "记忆并重复鼓点",
    icon: "🥁",
    theme: "--c-red",
    age: "3-6 岁",
    tag: "艺术·听觉",
  },
  {
    id: "fishing",
    title: "钓鱼",
    subtitle: "钓起指定的鱼",
    icon: "🎣",
    theme: "--c-cyan",
    age: "3-6 岁",
    tag: "反应·观察",
  },
  {
    id: "block-tower",
    title: "搭积木",
    subtitle: "把积木叠得又高又稳",
    icon: "🧱",
    theme: "--c-orange",
    age: "3-6 岁",
    tag: "精细·平衡",
  },
  {
    id: "word-chain",
    title: "词语接龙",
    subtitle: "首尾相接排词语",
    icon: "🔠",
    theme: "--c-purple",
    age: "5-6 岁",
    tag: "语言·词汇",
  },
  {
    id: "reverse-memory",
    title: "倒序记忆",
    subtitle: "记住后倒着点出来",
    icon: "🔄",
    theme: "--c-indigo",
    age: "5-6 岁",
    tag: "记忆·逆向",
  },
  {
    id: "claw",
    title: "抓娃娃机",
    subtitle: "抓准时机抓起玩偶",
    icon: "🧸",
    theme: "--c-pink",
    age: "3-6 岁",
    tag: "反应·时机",
  },
  {
    id: "bubble-shoot",
    title: "泡泡射击",
    subtitle: "瞄准发射消除同色",
    icon: "🫧",
    theme: "--c-cyan",
    age: "4-6 岁",
    tag: "瞄准·策略",
  },
  {
    id: "wheel",
    title: "幸运转盘",
    subtitle: "转盘停在哪个颜色",
    icon: "🎡",
    theme: "--c-orange",
    age: "3-6 岁",
    tag: "概率·反应",
  },
  {
    id: "pinball",
    title: "弹珠台",
    subtitle: "弹珠撞击得分",
    icon: "🔮",
    theme: "--c-purple",
    age: "4-6 岁",
    tag: "物理·弹射",
  },
  {
    id: "guess-card",
    title: "猜大小",
    subtitle: "翻牌猜下一张大或小",
    icon: "🃏",
    theme: "--c-red",
    age: "4-6 岁",
    tag: "概率·推理",
  },
  {
    id: "snake",
    title: "贪吃蛇",
    subtitle: "控制蛇吃食物变长",
    icon: "🐍",
    theme: "--c-green",
    age: "4-6 岁",
    tag: "控制·反应",
  },
  {
    id: "2048",
    title: "数字合并",
    subtitle: "滑动合并相同数字",
    icon: "🔢",
    theme: "--c-blue",
    age: "5-6 岁",
    tag: "策略·数字",
  },
  {
    id: "number-sequence",
    title: "数字序列",
    subtitle: "补全数列缺的数字",
    icon: "🔗",
    theme: "--c-teal",
    age: "5-6 岁",
    tag: "数学·规律",
  },
  {
    id: "pinyin-puzzle",
    title: "拼音拼图",
    subtitle: "把声母韵母拼成音节",
    icon: "🔤",
    theme: "--c-blue",
    age: "5-6 岁",
    tag: "语言·拼音",
  },
  {
    id: "radical",
    title: "部首配对",
    subtitle: "给部首找对应的字",
    icon: "🧩",
    theme: "--c-indigo",
    age: "5-6 岁",
    tag: "语言·汉字",
  },
  {
    id: "idiom",
    title: "成语填字",
    subtitle: "补全成语缺的字",
    icon: "📜",
    theme: "--c-purple",
    age: "5-6 岁",
    tag: "语言·成语",
  },
  {
    id: "measure-word",
    title: "量词搭配",
    subtitle: "一只、一条、一个",
    icon: "📏",
    theme: "--c-green",
    age: "4-6 岁",
    tag: "语言·量词",
  },
  {
    id: "stroke-order",
    title: "笔画顺序",
    subtitle: "按正确笔顺写字",
    icon: "✍️",
    theme: "--c-brown",
    age: "5-6 岁",
    tag: "语言·书写",
  },
  {
    id: "homophone",
    title: "同音字",
    subtitle: "辨析读音相同的字",
    icon: "🔊",
    theme: "--c-yellow",
    age: "5-6 岁",
    tag: "语言·辨析",
  },
  {
    id: "similar-char",
    title: "形近字",
    subtitle: "辨析长得很像的字",
    icon: "👀",
    theme: "--c-cyan",
    age: "5-6 岁",
    tag: "语言·辨析",
  },
  {
    id: "word-classify",
    title: "词语分类",
    subtitle: "把词语归到正确类别",
    icon: "🗂️",
    theme: "--c-teal",
    age: "4-6 岁",
    tag: "语言·分类",
  },
  {
    id: "fraction",
    title: "分数披萨",
    subtitle: "切披萨认识分数",
    icon: "🍕",
    theme: "--c-red",
    age: "5-6 岁",
    tag: "数学·分数",
  },
  {
    id: "time-timeline",
    title: "时间线",
    subtitle: "把事件按时间排序",
    icon: "⏳",
    theme: "--c-orange",
    age: "4-6 岁",
    tag: "认知·时间",
  },
  {
    id: "thermometer",
    title: "温度计",
    subtitle: "读取温度认识冷热",
    icon: "🌡️",
    theme: "--c-red",
    age: "4-6 岁",
    tag: "认知·测量",
  },
  {
    id: "calendar",
    title: "日历认知",
    subtitle: "认识星期和日期",
    icon: "📅",
    theme: "--c-blue",
    age: "5-6 岁",
    tag: "认知·日期",
  },
  {
    id: "money",
    title: "小小钱包",
    subtitle: "认识人民币换算",
    icon: "💰",
    theme: "--c-green",
    age: "5-6 岁",
    tag: "数学·货币",
  },
  {
    id: "ruler",
    title: "测量尺",
    subtitle: "用尺子量物品长度",
    icon: "📐",
    theme: "--c-teal",
    age: "4-6 岁",
    tag: "认知·测量",
  },
  {
    id: "symmetry-axis",
    title: "对称轴",
    subtitle: "判断图形的对称轴",
    icon: "✿",
    theme: "--c-pink",
    age: "5-6 岁",
    tag: "认知·几何",
  },
  {
    id: "3d-shape",
    title: "立体图形",
    subtitle: "认识立方体球体圆柱",
    icon: "🎲",
    theme: "--c-purple",
    age: "4-6 岁",
    tag: "认知·立体",
  },
  {
    id: "color-gradient",
    title: "颜色渐变",
    subtitle: "把颜色按深浅排序",
    icon: "🌈",
    theme: "--c-pink",
    age: "3-6 岁",
    tag: "认知·色彩",
  },
  {
    id: "spectrum",
    title: "光谱排序",
    subtitle: "按彩虹顺序排列颜色",
    icon: "🌠",
    theme: "--c-indigo",
    age: "4-6 岁",
    tag: "认知·科学",
  },
  {
    id: "constellation",
    title: "星座连线",
    subtitle: "连线画出星座图案",
    icon: "⭐",
    theme: "--c-indigo",
    age: "4-6 岁",
    tag: "科学·天文",
  },
  {
    id: "planet-orbit",
    title: "行星轨道",
    subtitle: "认识太阳系行星",
    icon: "🪐",
    theme: "--c-purple",
    age: "4-6 岁",
    tag: "科学·天文",
  },
  {
    id: "ecosystem",
    title: "食物链",
    subtitle: "排出谁吃谁的关系",
    icon: "🦊",
    theme: "--c-green",
    age: "5-6 岁",
    tag: "科学·生物",
  },
  {
    id: "weather-forecast",
    title: "天气预测",
    subtitle: "根据线索预测天气",
    icon: "⛈️",
    theme: "--c-cyan",
    age: "5-6 岁",
    tag: "科学·气象",
  },
  {
    id: "magnet-maze",
    title: "磁铁迷宫",
    subtitle: "磁力引导小球到终点",
    icon: "🧲",
    theme: "--c-red",
    age: "4-6 岁",
    tag: "科学·磁力",
  },
  {
    id: "circuit",
    title: "电路连通",
    subtitle: "连接电路让灯泡亮起",
    icon: "💡",
    theme: "--c-yellow",
    age: "5-6 岁",
    tag: "科学·电学",
  },
  {
    id: "bubble-wrap",
    title: "捏泡泡纸",
    subtitle: "尽情捏爆所有泡泡",
    icon: "🫧",
    theme: "--c-cyan",
    age: "3-6 岁",
    tag: "反应·解压",
  },
  {
    id: "feed-animals",
    title: "喂小动物",
    subtitle: "按食性喂对食物",
    icon: "🍖",
    theme: "--c-green",
    age: "3-5 岁",
    tag: "认知·生物",
  },
  {
    id: "trace-line",
    title: "描线小路",
    subtitle: "沿虚线画出路线",
    icon: "✏️",
    theme: "--c-purple",
    age: "3-6 岁",
    tag: "创造·精细",
  },
  {
    id: "balance-scale",
    title: "平衡秤",
    subtitle: "加减砝码让秤平衡",
    icon: "⚖️",
    theme: "--c-teal",
    age: "4-6 岁",
    tag: "数学·平衡",
  },
  {
    id: "sorting-hat",
    title: "分拣帽子",
    subtitle: "按多个维度分类物品",
    icon: "🎩",
    theme: "--c-indigo",
    age: "4-6 岁",
    tag: "逻辑·分类",
  },
  {
    id: "reaction-light",
    title: "亮灯反应",
    subtitle: "灯亮起就快点点它",
    icon: "🚦",
    theme: "--c-red",
    age: "3-6 岁",
    tag: "反应·速度",
  },
  {
    id: "pop-balloon",
    title: "戳气球",
    subtitle: "按颜色规则戳气球",
    icon: "🎈",
    theme: "--c-pink",
    age: "3-6 岁",
    tag: "反应·颜色",
  },
  {
    id: "make-face",
    title: "拼鬼脸",
    subtitle: "拖五官拼出表情",
    icon: "😀",
    theme: "--c-orange",
    age: "3-6 岁",
    tag: "创造·认知",
  },
  {
    id: "knock-blocks",
    title: "数积木",
    subtitle: "看图数出积木数量",
    icon: "🧱",
    theme: "--c-orange",
    age: "4-6 岁",
    tag: "数学·计数",
  },
  {
    id: "mirror-draw",
    title: "镜像画",
    subtitle: "对称地画另一半",
    icon: "🪞",
    theme: "--c-pink",
    age: "4-6 岁",
    tag: "创造·对称",
  },
  {
    id: "treasure-hunt",
    title: "翻牌寻宝",
    subtitle: "记住宝物藏在哪",
    icon: "💎",
    theme: "--c-yellow",
    age: "3-6 岁",
    tag: "记忆·寻宝",
  },
  {
    id: "pond-skip",
    title: "跳荷叶",
    subtitle: "按数字顺序跳过河",
    icon: "🐸",
    theme: "--c-green",
    age: "3-6 岁",
    tag: "数学·数序",
  },
  {
    id: "wind-mill",
    title: "风车转转",
    subtitle: "吹风让风车转起来",
    icon: "🌬️",
    theme: "--c-cyan",
    age: "3-5 岁",
    tag: "反应·因果",
  },
  {
    id: "garden-bloom",
    title: "小花园",
    subtitle: "浇水让种子开花",
    icon: "🌷",
    theme: "--c-pink",
    age: "3-6 岁",
    tag: "认知·生长",
  },
  {
    id: "ice-cream-stack",
    title: "叠甜筒",
    subtitle: "把球叠在甜筒上",
    icon: "🍦",
    theme: "--c-pink",
    age: "3-6 岁",
    tag: "反应·平衡",
  },
  {
    id: "fishing-rod",
    title: "拖竿钓鱼",
    subtitle: "拖鱼竿钓起小鱼",
    icon: "🎣",
    theme: "--c-blue",
    age: "3-6 岁",
    tag: "反应·拖拽",
  },
  {
    id: "egg-hatch",
    title: "破壳配对",
    subtitle: "蛋和动物配对",
    icon: "🥚",
    theme: "--c-yellow",
    age: "3-6 岁",
    tag: "认知·配对",
  },
  {
    id: "ladder-step",
    title: "跳格子",
    subtitle: "按规则跳到正确格子",
    icon: "🪜",
    theme: "--c-green",
    age: "4-6 岁",
    tag: "数学·数序",
  },
  {
    id: "color-traffic",
    title: "红绿灯",
    subtitle: "指挥车辆停和走",
    icon: "🚦",
    theme: "--c-red",
    age: "3-6 岁",
    tag: "认知·规则",
  },
  {
    id: "feed-monster-color",
    title: "色怪饿了",
    subtitle: "怪兽只吃指定颜色",
    icon: "👾",
    theme: "--c-purple",
    age: "3-6 岁",
    tag: "认知·颜色",
  },
  {
    id: "puzzle-rotate",
    title: "转转拼图",
    subtitle: "旋转碎片拼成图",
    icon: "🔄",
    theme: "--c-indigo",
    age: "4-6 岁",
    tag: "认知·空间",
  },
  {
    id: "rainbow-bridge",
    title: "彩虹桥",
    subtitle: "按颜色搭出彩虹桥",
    icon: "🌈",
    theme: "--c-pink",
    age: "3-6 岁",
    tag: "认知·色彩",
  },
  {
    id: "ant-march",
    title: "蚂蚁排队",
    subtitle: "按大小排好蚂蚁",
    icon: "🐜",
    theme: "--c-brown",
    age: "3-5 岁",
    tag: "认知·排序",
  },
  {
    id: "spin-bottle",
    title: "转瓶子",
    subtitle: "瓶子指向谁就做任务",
    icon: "🍾",
    theme: "--c-green",
    age: "3-6 岁",
    tag: "反应·社交",
  },
  {
    id: "fruit-weight",
    title: "水果秤",
    subtitle: "比较水果谁更重",
    icon: "🍎",
    theme: "--c-orange",
    age: "4-6 岁",
    tag: "认知·比较",
  },
  {
    id: "dino-bones",
    title: "恐龙骨头",
    subtitle: "按长短排好骨架",
    icon: "🦴",
    theme: "--c-brown",
    age: "4-6 岁",
    tag: "认知·排序",
  },
  {
    id: "moon-phase",
    title: "月亮变化",
    subtitle: "认识月相圆缺",
    icon: "🌙",
    theme: "--c-indigo",
    age: "4-6 岁",
    tag: "科学·天文",
  },
  {
    id: "leaf-sort",
    title: "捡落叶",
    subtitle: "按颜色形状分类",
    icon: "🍂",
    theme: "--c-orange",
    age: "3-5 岁",
    tag: "认知·分类",
  },
  {
    id: "bubble-pop-math",
    title: "算术泡泡",
    subtitle: "戳爆答案正确的泡泡",
    icon: "🫧",
    theme: "--c-blue",
    age: "5-6 岁",
    tag: "数学·运算",
  },
  {
    id: "shape-builder",
    title: "形状造物",
    subtitle: "用形状拼出图案",
    icon: "🔷",
    theme: "--c-purple",
    age: "4-6 岁",
    tag: "创造·空间",
  },
  {
    id: "sound-sequence",
    title: "声音记忆",
    subtitle: "记住声音发出的顺序",
    icon: "🔔",
    theme: "--c-teal",
    age: "4-6 岁",
    tag: "记忆·听觉",
  },
  {
    id: "candy-pattern",
    title: "糖果花纹",
    subtitle: "补全糖果的重复花纹",
    icon: "🍬",
    theme: "--c-pink",
    age: "4-6 岁",
    tag: "逻辑·规律",
  },
  {
    id: "dot-to-dot",
    title: "连点成图",
    subtitle: "按数字顺序连出图案",
    icon: "✏️",
    theme: "--c-blue",
    age: "4-6 岁",
    tag: "认知·数序",
  },
  {
    id: "flying-bird",
    title: "小鸟飞行",
    subtitle: "点击让小鸟避开障碍",
    icon: "🐦",
    theme: "--c-cyan",
    age: "3-6 岁",
    tag: "反应·控制",
  },
  {
    id: "color-train",
    title: "颜色火车",
    subtitle: "按颜色编组车厢",
    icon: "🚂",
    theme: "--c-orange",
    age: "3-5 岁",
    tag: "认知·颜色",
  },
  {
    id: "seed-sprout",
    title: "种子生长",
    subtitle: "排出植物生长顺序",
    icon: "🌱",
    theme: "--c-green",
    age: "3-6 岁",
    tag: "科学·生物",
  },
  {
    id: "moon-jump",
    title: "月球跳跃",
    subtitle: "低重力下跳过坑洞",
    icon: "🌕",
    theme: "--c-indigo",
    age: "3-6 岁",
    tag: "反应·物理",
  },
  {
    id: "bottle-cap",
    title: "瓶盖配对",
    subtitle: "把瓶盖拧回对应瓶子",
    icon: "🍶",
    theme: "--c-teal",
    age: "3-6 岁",
    tag: "认知·配对",
  },
  {
    id: "shadow-puppet",
    title: "手影猜谜",
    subtitle: "看手影猜是什么动物",
    icon: "🤚",
    theme: "--c-purple",
    age: "3-6 岁",
    tag: "认知·想象",
  },
  {
    id: "ice-melt",
    title: "冰块融化",
    subtitle: "排出融化先后顺序",
    icon: "🧊",
    theme: "--c-cyan",
    age: "4-6 岁",
    tag: "科学·物态",
  },
  {
    id: "balloon-math",
    title: "气球算术",
    subtitle: "升空前戳对答案气球",
    icon: "🎈",
    theme: "--c-pink",
    age: "5-6 岁",
    tag: "数学·运算",
  },
  {
    id: "fruit-basket",
    title: "水果凑数",
    subtitle: "选水果凑到目标数量",
    icon: "🧺",
    theme: "--c-green",
    age: "4-6 岁",
    tag: "数学·加法",
  },
  {
    id: "traffic-jam",
    title: "移车出库",
    subtitle: "滑动汽车让目标车出库",
    icon: "🚗",
    theme: "--c-red",
    age: "4-6 岁",
    tag: "逻辑·策略",
  },
  {
    id: "piano-keys",
    title: "认琴键",
    subtitle: "听音找对应琴键",
    icon: "🎹",
    theme: "--c-purple",
    age: "4-6 岁",
    tag: "艺术·音乐",
  },
  {
    id: "cloud-shape",
    title: "云朵想象",
    subtitle: "云朵像什么就选什么",
    icon: "☁️",
    theme: "--c-cyan",
    age: "3-6 岁",
    tag: "创造·想象",
  },
  {
    id: "ant-farm",
    title: "蚂蚁搬家",
    subtitle: "画出蚂蚁搬运路线",
    icon: "🐜",
    theme: "--c-brown",
    age: "4-6 岁",
    tag: "逻辑·路径",
  },
  {
    id: "egg-carton",
    title: "蛋盒计数",
    subtitle: "看蛋盒数有几颗蛋",
    icon: "🥚",
    theme: "--c-yellow",
    age: "3-5 岁",
    tag: "数学·计数",
  },
  {
    id: "lily-pad-math",
    title: "荷叶算术",
    subtitle: "跳到答案正确的荷叶",
    icon: "🐸",
    theme: "--c-green",
    age: "5-6 岁",
    tag: "数学·运算",
  },
  {
    id: "rainbow-slide",
    title: "彩虹滑道",
    subtitle: "按颜色顺序排滑道",
    icon: "🌈",
    theme: "--c-pink",
    age: "3-6 岁",
    tag: "认知·色彩",
  },
  {
    id: "cookie-count",
    title: "数饼干",
    subtitle: "罐子里有几块饼干",
    icon: "🍪",
    theme: "--c-orange",
    age: "3-5 岁",
    tag: "数学·计数",
  },
  {
    id: "block-pattern",
    title: "积木规律塔",
    subtitle: "补全积木的重复规律",
    icon: "🧱",
    theme: "--c-orange",
    age: "4-6 岁",
    tag: "逻辑·规律",
  },
  {
    id: "fish-school",
    title: "鱼群分组",
    subtitle: "按数量把鱼分成组",
    icon: "🐟",
    theme: "--c-blue",
    age: "4-6 岁",
    tag: "数学·分组",
  },
  {
    id: "star-map",
    title: "星图连线",
    subtitle: "连星画出动物星座",
    icon: "✨",
    theme: "--c-indigo",
    age: "4-6 岁",
    tag: "科学·天文",
  },
  {
    id: "weather-dress",
    title: "出门穿衣",
    subtitle: "看天气选全套穿搭",
    icon: "🧥",
    theme: "--c-teal",
    age: "3-6 岁",
    tag: "认知·生活",
  },
  {
    id: "grocery-store",
    title: "超市找零",
    subtitle: "买东西算该找多少钱",
    icon: "🛒",
    theme: "--c-green",
    age: "5-6 岁",
    tag: "数学·货币",
  },
  {
    id: "pet-vet",
    title: "宠物医生",
    subtitle: "对症给小动物治疗",
    icon: "🩺",
    theme: "--c-red",
    age: "3-6 岁",
    tag: "认知·配对",
  },
  {
    id: "construction",
    title: "建筑工地",
    subtitle: "按图纸搭出建筑",
    icon: "🏗️",
    theme: "--c-brown",
    age: "4-6 岁",
    tag: "创造·空间",
  },
  {
    id: "butterfly-wing",
    title: "蝴蝶翅膀",
    subtitle: "补全翅膀的对称花纹",
    icon: "🦋",
    theme: "--c-purple",
    age: "4-6 岁",
    tag: "认知·对称",
  },
  {
    id: "snail-race",
    title: "蜗牛赛跑",
    subtitle: "谁的蜗牛最慢谁赢",
    icon: "🐌",
    theme: "--c-green",
    age: "3-6 岁",
    tag: "反应·逆向",
  },
  {
    id: "volcano-sort",
    title: "火山喷发",
    subtitle: "排出火山活动顺序",
    icon: "🌋",
    theme: "--c-red",
    age: "4-6 岁",
    tag: "科学·地理",
  },
  {
    id: "clock-chime",
    title: "时钟报时",
    subtitle: "听钟声数几下是几点",
    icon: "🕰️",
    theme: "--c-yellow",
    age: "5-6 岁",
    tag: "认知·时间",
  },
  {
    id: "picnic-ants",
    title: "野餐蚂蚁",
    subtitle: "把食物平均分给蚂蚁",
    icon: "🧺",
    theme: "--c-brown",
    age: "4-6 岁",
    tag: "数学·除法",
  },
  {
    id: "dino-hatch",
    title: "恐龙蛋",
    subtitle: "大小蛋匹配大恐龙",
    icon: "🥚",
    theme: "--c-green",
    age: "3-6 岁",
    tag: "认知·配对",
  },
  {
    id: "orchard-pick",
    title: "果园采摘",
    subtitle: "按成熟顺序摘水果",
    icon: "🍎",
    theme: "--c-green",
    age: "3-6 岁",
    tag: "认知·排序",
  },
  {
    id: "puppy-run",
    title: "小狗跑酷",
    subtitle: "跳跃躲过障碍",
    icon: "🐕",
    theme: "--c-orange",
    age: "3-6 岁",
    tag: "反应·控制",
  },
  {
    id: "helicopter",
    title: "直升机救援",
    subtitle: "吊起遇险的小动物",
    icon: "🚁",
    theme: "--c-cyan",
    age: "3-6 岁",
    tag: "反应·拖拽",
  },
  {
    id: "magic-hat",
    title: "魔术帽",
    subtitle: "猜猜球藏在哪顶帽下",
    icon: "🎩",
    theme: "--c-purple",
    age: "3-6 岁",
    tag: "记忆·追踪",
  },
  {
    id: "gumball",
    title: "弹珠机",
    subtitle: "接住指定颜色的弹珠",
    icon: "🔮",
    theme: "--c-pink",
    age: "3-6 岁",
    tag: "反应·颜色",
  },
  {
    id: "telescope",
    title: "望远镜",
    subtitle: "在星空中找到指定星星",
    icon: "🔭",
    theme: "--c-indigo",
    age: "3-6 岁",
    tag: "专注·观察",
  },
  {
    id: "conveyor",
    title: "传送带",
    subtitle: "把物品分拣到对的筐",
    icon: "⚙️",
    theme: "--c-teal",
    age: "3-6 岁",
    tag: "反应·分类",
  },
  {
    id: "domino",
    title: "多米诺",
    subtitle: "按点数排好骨牌",
    icon: "🁫",
    theme: "--c-brown",
    age: "4-6 岁",
    tag: "数学·排序",
  },
  {
    id: "sushi-roll",
    title: "寿司卷",
    subtitle: "按顺序放进配料",
    icon: "🍣",
    theme: "--c-red",
    age: "3-6 岁",
    tag: "记忆·顺序",
  },
  {
    id: "pizza-top",
    title: "披萨配料",
    subtitle: "照订单放对配料",
    icon: "🍕",
    theme: "--c-orange",
    age: "3-6 岁",
    tag: "认知·配对",
  },
  {
    id: "rocket-launch",
    title: "火箭发射",
    subtitle: "倒计时按对数字",
    icon: "🚀",
    theme: "--c-blue",
    age: "3-6 岁",
    tag: "数学·倒数",
  },
  {
    id: "zoo-keeper",
    title: "动物园长",
    subtitle: "把动物送回正确的笼",
    icon: "🦁",
    theme: "--c-green",
    age: "3-6 岁",
    tag: "认知·分类",
  },
  {
    id: "firefighter",
    title: "消防员",
    subtitle: "喷水灭掉所有火苗",
    icon: "🧯",
    theme: "--c-red",
    age: "3-6 岁",
    tag: "反应·点击",
  },
  {
    id: "postman",
    title: "邮递员",
    subtitle: "按门牌号送对信",
    icon: "📮",
    theme: "--c-blue",
    age: "4-6 岁",
    tag: "数学·配对",
  },
  {
    id: "barber-shop",
    title: "理发师",
    subtitle: "照图剪出一样的发型",
    icon: "💈",
    theme: "--c-pink",
    age: "3-6 岁",
    tag: "认知·配对",
  },
  {
    id: "baker",
    title: "面包师",
    subtitle: "按订单数量装面包",
    icon: "🥖",
    theme: "--c-orange",
    age: "4-6 岁",
    tag: "数学·计数",
  },
  {
    id: "astronaut",
    title: "修飞船",
    subtitle: "把零件装回正确位置",
    icon: "🧑‍🚀",
    theme: "--c-indigo",
    age: "4-6 岁",
    tag: "认知·配对",
  },
  {
    id: "submarine",
    title: "潜水艇",
    subtitle: "上浮下潜避开水雷",
    icon: "🚤",
    theme: "--c-cyan",
    age: "3-6 岁",
    tag: "反应·控制",
  },
  {
    id: "safari-photo",
    title: "野生动物",
    subtitle: "拍到指定的动物",
    icon: "📷",
    theme: "--c-green",
    age: "3-6 岁",
    tag: "反应·观察",
  },
  {
    id: "farm-harvest",
    title: "农场收成",
    subtitle: "按季节收对应作物",
    icon: "🌾",
    theme: "--c-green",
    age: "4-6 岁",
    tag: "认知·分类",
  },
  {
    id: "laundry",
    title: "洗衣服",
    subtitle: "按颜色分开衣物",
    icon: "🧺",
    theme: "--c-cyan",
    age: "3-5 岁",
    tag: "认知·分类",
  },
  {
    id: "library",
    title: "图书馆",
    subtitle: "按类别把书归架",
    icon: "📚",
    theme: "--c-indigo",
    age: "4-6 岁",
    tag: "认知·分类",
  },
  {
    id: "recycle",
    title: "垃圾分类",
    subtitle: "扔进对的回收桶",
    icon: "♻️",
    theme: "--c-green",
    age: "3-6 岁",
    tag: "认知·分类",
  },
  {
    id: "hospital",
    title: "小医院",
    subtitle: "按病情分到对的科室",
    icon: "🏥",
    theme: "--c-red",
    age: "4-6 岁",
    tag: "认知·配对",
  },
  {
    id: "kitchen",
    title: "小厨房",
    subtitle: "按正确顺序备菜",
    icon: "🍳",
    theme: "--c-orange",
    age: "3-6 岁",
    tag: "记忆·顺序",
  },
  {
    id: "shoe-shop",
    title: "鞋店",
    subtitle: "给左右脚配对鞋子",
    icon: "👞",
    theme: "--c-brown",
    age: "3-6 岁",
    tag: "认知·配对",
  },
  {
    id: "florist",
    title: "花店",
    subtitle: "照花束图插一样的花",
    icon: "💐",
    theme: "--c-pink",
    age: "3-6 岁",
    tag: "认知·规律",
  },
  {
    id: "toy-fix",
    title: "修玩具",
    subtitle: "给玩具装回缺的零件",
    icon: "🧸",
    theme: "--c-purple",
    age: "4-6 岁",
    tag: "认知·配对",
  },
  {
    id: "jewelry",
    title: "串珠子",
    subtitle: "按规律串出项链",
    icon: "📿",
    theme: "--c-purple",
    age: "4-6 岁",
    tag: "逻辑·规律",
  },
  {
    id: "origami",
    title: "折纸",
    subtitle: "按步骤折出作品",
    icon: "📄",
    theme: "--c-pink",
    age: "4-6 岁",
    tag: "记忆·顺序",
  },
  {
    id: "pottery",
    title: "陶艺",
    subtitle: "塑出一样的形状",
    icon: "🏺",
    theme: "--c-brown",
    age: "3-6 岁",
    tag: "认知·配对",
  },
  {
    id: "stained-glass",
    title: "彩窗",
    subtitle: "用碎片拼出彩色窗",
    icon: "🪟",
    theme: "--c-cyan",
    age: "4-6 岁",
    tag: "创造·拼图",
  },
  {
    id: "carousel",
    title: "旋转木马",
    subtitle: "找到指定颜色的木马",
    icon: "🎠",
    theme: "--c-pink",
    age: "3-6 岁",
    tag: "反应·观察",
  },
  {
    id: "fruit-slicer",
    title: "切水果",
    subtitle: "划过切开水果避开炸弹",
    icon: "🍉",
    theme: "--c-red",
    age: "3-6 岁",
    tag: "反应·切割",
  },
  {
    id: "ninja-jump",
    title: "忍者跳",
    subtitle: "二段跳越过障碍",
    icon: "🥷",
    theme: "--c-indigo",
    age: "3-6 岁",
    tag: "反应·控制",
  },
  {
    id: "boulder-dash",
    title: "躲滚石",
    subtitle: "左右移动躲开滚石",
    icon: "🪨",
    theme: "--c-brown",
    age: "3-6 岁",
    tag: "反应·躲避",
  },
  {
    id: "spider-web",
    title: "蜘蛛网",
    subtitle: "连线织出蜘蛛网",
    icon: "🕷️",
    theme: "--c-purple",
    age: "4-6 岁",
    tag: "创造·连线",
  },
  {
    id: "dune-bug",
    title: "沙虫",
    subtitle: "左右钻沙避开仙人掌",
    icon: "🐛",
    theme: "--c-orange",
    age: "3-6 岁",
    tag: "反应·躲避",
  },
  {
    id: "cloud-hop",
    title: "踩云跳",
    subtitle: "踩着云朵往上跳",
    icon: "☁️",
    theme: "--c-cyan",
    age: "3-6 岁",
    tag: "反应·时机",
  },
  {
    id: "dragon-breath",
    title: "龙焰",
    subtitle: "喷火吹灭所有蜡烛",
    icon: "🐉",
    theme: "--c-red",
    age: "3-6 岁",
    tag: "反应·瞄准",
  },
  {
    id: "ocean-clean",
    title: "海洋清理",
    subtitle: "捞垃圾放走鱼",
    icon: "🌊",
    theme: "--c-blue",
    age: "3-6 岁",
    tag: "反应·分类",
  },
  {
    id: "tree-climber",
    title: "爬树赛",
    subtitle: "左右交替往上爬",
    icon: "🌳",
    theme: "--c-green",
    age: "3-6 岁",
    tag: "反应·交替",
  },
  {
    id: "mole-town",
    title: "鼹鼠洞",
    subtitle: "数有几只鼹鼠出洞",
    icon: "🦫",
    theme: "--c-brown",
    age: "3-5 岁",
    tag: "数学·计数",
  },
  {
    id: "bee-garden",
    title: "采蜜",
    subtitle: "采对应颜色的花蜜",
    icon: "🐝",
    theme: "--c-yellow",
    age: "3-6 岁",
    tag: "认知·颜色",
  },
  {
    id: "mushroom-hop",
    title: "蘑菇跳",
    subtitle: "跳过毒蘑菇只踩好蘑菇",
    icon: "🍄",
    theme: "--c-red",
    age: "3-6 岁",
    tag: "反应·判断",
  },
  {
    id: "star-catch",
    title: "捞星星",
    subtitle: "移动网兜捞星星",
    icon: "⭐",
    theme: "--c-indigo",
    age: "3-6 岁",
    tag: "反应·接物",
  },
  {
    id: "leaf-vein",
    title: "叶脉",
    subtitle: "补全叶子的对称叶脉",
    icon: "🍃",
    theme: "--c-green",
    age: "4-6 岁",
    tag: "认知·对称",
  },
  {
    id: "rainbow-pour",
    title: "彩虹水",
    subtitle: "按比例调出目标色水",
    icon: "🧪",
    theme: "--c-purple",
    age: "4-6 岁",
    tag: "认知·颜色",
  },
  {
    id: "crystal-sort",
    title: "水晶",
    subtitle: "按光泽从暗到亮排序",
    icon: "💎",
    theme: "--c-cyan",
    age: "3-6 岁",
    tag: "认知·排序",
  },
  {
    id: "puzzle-slide-maze",
    title: "滑块迷宫",
    subtitle: "推滑块走到终点",
    icon: "🧩",
    theme: "--c-indigo",
    age: "4-6 岁",
    tag: "逻辑·策略",
  },
  {
    id: "color-recipe",
    title: "调色配方",
    subtitle: "按配方加对应色滴",
    icon: "🎨",
    theme: "--c-pink",
    age: "4-6 岁",
    tag: "认知·颜色",
  },
  {
    id: "music-echo",
    title: "音乐回声",
    subtitle: "听完再复奏一遍",
    icon: "🎼",
    theme: "--c-purple",
    age: "4-6 岁",
    tag: "记忆·听觉",
  },
  {
    id: "shape-shadow-trace",
    title: "描轮廓",
    subtitle: "沿轮廓描出图形",
    icon: "✏️",
    theme: "--c-teal",
    age: "3-6 岁",
    tag: "创造·精细",
  },
  {
    id: "number-bridge",
    title: "数字桥",
    subtitle: "按数字顺序搭桥过河",
    icon: "🌉",
    theme: "--c-blue",
    age: "4-6 岁",
    tag: "数学·数序",
  },
  {
    id: "word-bubble",
    title: "词语泡",
    subtitle: "把同义词泡归一类",
    icon: "💭",
    theme: "--c-indigo",
    age: "5-6 岁",
    tag: "语言·分类",
  },
  {
    id: "animal-home",
    title: "动物的家",
    subtitle: "动物住在哪里",
    icon: "🏠",
    theme: "--c-green",
    age: "3-6 岁",
    tag: "认知·配对",
  },
  {
    id: "seasons-wheel",
    title: "季节转盘",
    subtitle: "按季节选对应景物",
    icon: "🍂",
    theme: "--c-orange",
    age: "4-6 岁",
    tag: "认知·时令",
  },
  {
    id: "day-night",
    title: "昼夜",
    subtitle: "白天夜晚活动分类",
    icon: "🌞",
    theme: "--c-yellow",
    age: "3-6 岁",
    tag: "认知·分类",
  },
  {
    id: "tool-match",
    title: "工具配对",
    subtitle: "工具和职业配对",
    icon: "🔨",
    theme: "--c-brown",
    age: "4-6 岁",
    tag: "认知·配对",
  },
  {
    id: "emotion-story",
    title: "情绪故事",
    subtitle: "按故事排出情绪变化",
    icon: "📖",
    theme: "--c-pink",
    age: "4-6 岁",
    tag: "社交·情商",
  },
  {
    id: "size-recipe",
    title: "按量分",
    subtitle: "大小碗分对应分量",
    icon: "🥣",
    theme: "--c-orange",
    age: "3-5 岁",
    tag: "认知·大小",
  },
  {
    id: "speed-typing",
    title: "字母快打",
    subtitle: "快速点出显示的字母",
    icon: "⌨️",
    theme: "--c-blue",
    age: "4-6 岁",
    tag: "反应·字母",
  },
  {
    id: "memory-tray",
    title: "托盘记忆",
    subtitle: "记住托盘里的物品",
    icon: "🍽️",
    theme: "--c-teal",
    age: "4-6 岁",
    tag: "记忆·观察",
  },
  {
    id: "price-tag",
    title: "看标签",
    subtitle: "看价标付对应的钱",
    icon: "🏷️",
    theme: "--c-green",
    age: "5-6 岁",
    tag: "数学·货币",
  },
  {
    id: "shape-count",
    title: "数图形",
    subtitle: "图里有几个三角形",
    icon: "🔺",
    theme: "--c-purple",
    age: "4-6 岁",
    tag: "数学·计数",
  },
  {
    id: "bouncy-ball",
    title: "弹球躲刺",
    subtitle: "控制弹球避开尖刺",
    icon: "⚽",
    theme: "--c-orange",
    age: "3-6 岁",
    tag: "反应·控制",
  },
  {
    id: "flame-jump",
    title: "跳火焰",
    subtitle: "跳过一排火焰",
    icon: "🔥",
    theme: "--c-red",
    age: "3-6 岁",
    tag: "反应·时机",
  },
  {
    id: "ice-slide",
    title: "冰面滑",
    subtitle: "冰面上滑到指定位置",
    icon: "🧊",
    theme: "--c-cyan",
    age: "4-6 岁",
    tag: "逻辑·策略",
  },
  {
    id: "wind-push",
    title: "吹箱子",
    subtitle: "吹风把箱子推到目标",
    icon: "🌬️",
    theme: "--c-cyan",
    age: "4-6 岁",
    tag: "逻辑·策略",
  },
  {
    id: "light-maze",
    title: "光线迷宫",
    subtitle: "用镜子反射光线到目标",
    icon: "💡",
    theme: "--c-yellow",
    age: "5-6 岁",
    tag: "逻辑·光学",
  },
  {
    id: "mirror-room",
    title: "镜面房间",
    subtitle: "在镜子里找出口",
    icon: "🪞",
    theme: "--c-purple",
    age: "4-6 岁",
    tag: "逻辑·空间",
  },
  {
    id: "gear-spin",
    title: "齿轮方向",
    subtitle: "判断齿轮转向",
    icon: "⚙️",
    theme: "--c-brown",
    age: "5-6 岁",
    tag: "逻辑·机械",
  },
  {
    id: "lever-balance",
    title: "杠杆",
    subtitle: "力臂长短与平衡",
    icon: "⚖️",
    theme: "--c-teal",
    age: "5-6 岁",
    tag: "科学·物理",
  },
  {
    id: "pulley-lift",
    title: "滑轮",
    subtitle: "用滑轮吊起重物",
    icon: "🪢",
    theme: "--c-brown",
    age: "4-6 岁",
    tag: "科学·物理",
  },
  {
    id: "ramp-roll",
    title: "斜坡赛",
    subtitle: "谁的球滚得更快",
    icon: "🛹",
    theme: "--c-orange",
    age: "3-6 岁",
    tag: "科学·物理",
  },
  {
    id: "pendulum-swing",
    title: "钟摆",
    subtitle: "抓住摆动的奖励",
    icon: "⚖️",
    theme: "--c-indigo",
    age: "3-6 岁",
    tag: "反应·物理",
  },
  {
    id: "spring-bounce",
    title: "弹簧",
    subtitle: "压弹簧弹到目标高度",
    icon: "🌀",
    theme: "--c-green",
    age: "3-6 岁",
    tag: "反应·物理",
  },
  {
    id: "compass-find",
    title: "指南针",
    subtitle: "按指南针走对方向",
    icon: "🧭",
    theme: "--c-red",
    age: "4-6 岁",
    tag: "认知·方向",
  },
  {
    id: "map-read",
    title: "看地图",
    subtitle: "按地图走到宝藏",
    icon: "🗺️",
    theme: "--c-green",
    age: "4-6 岁",
    tag: "认知·空间",
  },
  {
    id: "flag-semaphore",
    title: "旗语",
    subtitle: "看旗子姿势认字母",
    icon: "🚩",
    theme: "--c-red",
    age: "5-6 岁",
    tag: "语言·符号",
  },
  {
    id: "morse-code",
    title: "摩斯码",
    subtitle: "听长短声辨字母",
    icon: "📡",
    theme: "--c-indigo",
    age: "5-6 岁",
    tag: "语言·符号",
  },
  {
    id: "clock-tower",
    title: "钟楼",
    subtitle: "两座钟哪个时间对",
    icon: "🏙️",
    theme: "--c-yellow",
    age: "5-6 岁",
    tag: "认知·时间",
  },
  {
    id: "calendar-event",
    title: "排日程",
    subtitle: "把活动排到正确日期",
    icon: "📅",
    theme: "--c-blue",
    age: "5-6 岁",
    tag: "认知·日期",
  },
  {
    id: "sand-timer",
    title: "沙漏",
    subtitle: "哪个沙漏漏得更快",
    icon: "⏳",
    theme: "--c-orange",
    age: "4-6 岁",
    tag: "认知·时间",
  },
  {
    id: "thermometer-dress",
    title: "温度穿衣",
    subtitle: "看温度选合适衣服",
    icon: "🌡️",
    theme: "--c-red",
    age: "4-6 岁",
    tag: "认知·生活",
  },
  {
    id: "shadow-clock",
    title: "日晷",
    subtitle: "看影子判断时间",
    icon: "🌇",
    theme: "--c-orange",
    age: "5-6 岁",
    tag: "科学·天文",
  },
  {
    id: "rainbow-order",
    title: "彩虹复原",
    subtitle: "把打乱的彩虹排回去",
    icon: "🌈",
    theme: "--c-pink",
    age: "3-6 岁",
    tag: "认知·色彩",
  },
  {
    id: "color-mix-advanced",
    title: "进阶调色",
    subtitle: "调出指定的高级色",
    icon: "🎨",
    theme: "--c-purple",
    age: "5-6 岁",
    tag: "认知·颜色",
  },
  {
    id: "pixel-art",
    title: "像素画",
    subtitle: "按数字填色画像素图",
    icon: "🖌️",
    theme: "--c-green",
    age: "4-6 岁",
    tag: "创造·艺术",
  },
  {
    id: "mosaic",
    title: "马赛克",
    subtitle: "用色块拼出图案",
    icon: "🟦",
    theme: "--c-cyan",
    age: "4-6 岁",
    tag: "创造·拼图",
  },
  {
    id: "stitch-pattern",
    title: "十字绣",
    subtitle: "按规律绣出花纹",
    icon: "🧵",
    theme: "--c-pink",
    age: "4-6 岁",
    tag: "创造·规律",
  },
  {
    id: "bead-abacus",
    title: "算盘",
    subtitle: "拨算盘珠做加法",
    icon: "🧮",
    theme: "--c-brown",
    age: "5-6 岁",
    tag: "数学·运算",
  },
  {
    id: "math-balance",
    title: "数字天平",
    subtitle: "两边数字相加要相等",
    icon: "⚖️",
    theme: "--c-teal",
    age: "5-6 岁",
    tag: "数学·平衡",
  },
  {
    id: "fraction-cake",
    title: "分蛋糕",
    subtitle: "把蛋糕分成等份",
    icon: "🍰",
    theme: "--c-pink",
    age: "4-6 岁",
    tag: "数学·分数",
  },
  {
    id: "geometry-tangram-2",
    title: "进阶七巧板",
    subtitle: "拼出更复杂的图案",
    icon: "📐",
    theme: "--c-indigo",
    age: "5-6 岁",
    tag: "创造·空间",
  },
  {
    id: "volume-pour",
    title: "量杯",
    subtitle: "倒出指定体积的水",
    icon: "🧪",
    theme: "--c-cyan",
    age: "5-6 岁",
    tag: "数学·体积",
  },
  {
    id: "duck-pond",
    title: "鸭塘数鸭",
    subtitle: "水面上有几只鸭子",
    icon: "🦆",
    theme: "--c-cyan",
    age: "3-5 岁",
    tag: "数学·计数",
  },
  {
    id: "lighthouse",
    title: "灯塔",
    subtitle: "旋转光束照亮船",
    icon: "🗼",
    theme: "--c-yellow",
    age: "3-6 岁",
    tag: "反应·时机",
  },
  {
    id: "bridge-build",
    title: "搭桥",
    subtitle: "选木板搭过河",
    icon: "🌉",
    theme: "--c-brown",
    age: "4-6 岁",
    tag: "逻辑·策略",
  },
  {
    id: "cave-explore",
    title: "洞穴探路",
    subtitle: "在黑暗洞穴找路",
    icon: "🕳️",
    theme: "--c-indigo",
    age: "4-6 岁",
    tag: "逻辑·空间",
  },
  {
    id: "jungle-vine",
    title: "藤蔓摆",
    subtitle: "摆荡跳到对面",
    icon: "🌿",
    theme: "--c-green",
    age: "3-6 岁",
    tag: "反应·时机",
  },
  {
    id: "volcano-escape",
    title: "火山逃生",
    subtitle: "快速跑出火山口",
    icon: "🌋",
    theme: "--c-red",
    age: "3-6 岁",
    tag: "反应·控制",
  },
  {
    id: "frost-slide",
    title: "冰滑迷宫",
    subtitle: "滑到指定位置",
    icon: "❄️",
    theme: "--c-cyan",
    age: "4-6 岁",
    tag: "逻辑·策略",
  },
  {
    id: "magnet-fish",
    title: "磁铁钓鱼",
    subtitle: "钓对应颜色的鱼",
    icon: "🧲",
    theme: "--c-red",
    age: "3-6 岁",
    tag: "反应·颜色",
  },
  {
    id: "echo-cave",
    title: "回声洞",
    subtitle: "听回声判断方向",
    icon: "📢",
    theme: "--c-purple",
    age: "4-6 岁",
    tag: "认知·听觉",
  },
  {
    id: "gravity-flip",
    title: "翻转重力",
    subtitle: "上下翻转到达终点",
    icon: "🔄",
    theme: "--c-indigo",
    age: "4-6 岁",
    tag: "反应·策略",
  },
  {
    id: "bubble-trap",
    title: "泡泡困虫",
    subtitle: "用泡泡圈住虫子",
    icon: "🫧",
    theme: "--c-cyan",
    age: "3-6 岁",
    tag: "反应·瞄准",
  },
  {
    id: "shadow-tag",
    title: "影子追逃",
    subtitle: "踩别人的影子",
    icon: "👤",
    theme: "--c-purple",
    age: "3-6 岁",
    tag: "反应·追逐",
  },
  {
    id: "petal-count",
    title: "数花瓣",
    subtitle: "花有几片花瓣",
    icon: "🌼",
    theme: "--c-pink",
    age: "3-5 岁",
    tag: "数学·计数",
  },
  {
    id: "shell-game",
    title: "贝壳猜珠",
    subtitle: "珠子藏在哪个贝壳",
    icon: "🐚",
    theme: "--c-orange",
    age: "3-6 岁",
    tag: "记忆·追踪",
  },
  {
    id: "candle-blow",
    title: "吹蜡烛",
    subtitle: "按数字吹灭蜡烛",
    icon: "🕯️",
    theme: "--c-yellow",
    age: "4-6 岁",
    tag: "数学·计数",
  },
  {
    id: "feather-fall",
    title: "接羽毛",
    subtitle: "接住飘落的羽毛",
    icon: "🪶",
    theme: "--c-teal",
    age: "3-6 岁",
    tag: "反应·接物",
  },
  {
    id: "barn-shape",
    title: "谷仓形状",
    subtitle: "按形状归仓",
    icon: "🏚️",
    theme: "--c-brown",
    age: "3-5 岁",
    tag: "认知·形状",
  },
  {
    id: "tide-pool",
    title: "潮汐池",
    subtitle: "海陆生物分类",
    icon: "🏖️",
    theme: "--c-cyan",
    age: "4-6 岁",
    tag: "认知·分类",
  },
  {
    id: "cloud-count",
    title: "数云朵",
    subtitle: "天上有几朵云",
    icon: "☁️",
    theme: "--c-blue",
    age: "3-5 岁",
    tag: "数学·计数",
  },
  {
    id: "raindrop-math",
    title: "雨滴算术",
    subtitle: "接住答案对的雨滴",
    icon: "🌧️",
    theme: "--c-blue",
    age: "5-6 岁",
    tag: "数学·运算",
  },
  {
    id: "maple-leaf",
    title: "枫叶找同",
    subtitle: "找出相同的枫叶",
    icon: "🍁",
    theme: "--c-orange",
    age: "3-6 岁",
    tag: "认知·观察",
  },
  {
    id: "snowflake-match",
    title: "雪花配",
    subtitle: "配对相同的雪花",
    icon: "❄️",
    theme: "--c-cyan",
    age: "3-6 岁",
    tag: "认知·配对",
  },
  {
    id: "pumpkin-sort",
    title: "南瓜排",
    subtitle: "按大小排南瓜",
    icon: "🎃",
    theme: "--c-orange",
    age: "3-5 岁",
    tag: "认知·排序",
  },
  {
    id: "scarecrow-dress",
    title: "稻草人",
    subtitle: "给稻草人穿搭",
    icon: "🧑‍🌾",
    theme: "--c-brown",
    age: "3-6 岁",
    tag: "创造·穿搭",
  },
  {
    id: "harvest-weight",
    title: "收成称",
    subtitle: "比较收成轻重",
    icon: "⚖️",
    theme: "--c-green",
    age: "4-6 岁",
    tag: "认知·比较",
  },
  {
    id: "cider-pour",
    title: "果汁量",
    subtitle: "按量倒果汁",
    icon: "🧃",
    theme: "--c-orange",
    age: "4-6 岁",
    tag: "数学·体积",
  },
  {
    id: "hay-bale-jump",
    title: "干草跳",
    subtitle: "跳过干草垛",
    icon: "🌾",
    theme: "--c-yellow",
    age: "3-6 岁",
    tag: "反应·跳跃",
  },
  {
    id: "corn-maze-mini",
    title: "玉米迷宫",
    subtitle: "穿过玉米田迷宫",
    icon: "🌽",
    theme: "--c-yellow",
    age: "4-6 岁",
    tag: "逻辑·迷宫",
  },
  {
    id: "apple-pick",
    title: "摘苹果",
    subtitle: "摘到最多苹果",
    icon: "🍎",
    theme: "--c-red",
    age: "3-6 岁",
    tag: "反应·收集",
  },
  {
    id: "barn-door",
    title: "谷仓门",
    subtitle: "给门涂对应颜色",
    icon: "🚪",
    theme: "--c-brown",
    age: "3-5 岁",
    tag: "认知·颜色",
  },
  {
    id: "chicken-count",
    title: "数小鸡",
    subtitle: "鸡舍有几只小鸡",
    icon: "🐔",
    theme: "--c-yellow",
    age: "3-5 岁",
    tag: "数学·计数",
  },
  {
    id: "tractor-park",
    title: "泊拖拉机",
    subtitle: "倒车停进车位",
    icon: "🚜",
    theme: "--c-red",
    age: "4-6 岁",
    tag: "逻辑·空间",
  },
  {
    id: "dolphin-jump",
    title: "海豚跳圈",
    subtitle: "海豚穿过圆圈",
    icon: "🐬",
    theme: "--c-cyan",
    age: "3-6 岁",
    tag: "反应·时机",
  },
  {
    id: "crab-walk",
    title: "螃蟹横走",
    subtitle: "横着走避开障碍",
    icon: "🦀",
    theme: "--c-orange",
    age: "3-6 岁",
    tag: "反应·控制",
  },
  {
    id: "owl-hoot",
    title: "猫头鹰",
    subtitle: "听叫声判断时间",
    icon: "🦉",
    theme: "--c-indigo",
    age: "4-6 岁",
    tag: "认知·听觉",
  },
  {
    id: "fox-sneak",
    title: "狐狸潜行",
    subtitle: "悄悄走不被发现",
    icon: "🦊",
    theme: "--c-orange",
    age: "3-6 岁",
    tag: "反应·时机",
  },
  {
    id: "deer-watch",
    title: "数鹿群",
    subtitle: "树林里有几只鹿",
    icon: "🦌",
    theme: "--c-brown",
    age: "3-5 岁",
    tag: "数学·计数",
  },
  {
    id: "koala-climb",
    title: "考拉爬树",
    subtitle: "交替点手脚往上爬",
    icon: "🐨",
    theme: "--c-green",
    age: "3-6 岁",
    tag: "反应·交替",
  },
  {
    id: "penguin-slide",
    title: "企鹅滑",
    subtitle: "滑行躲开冰缝",
    icon: "🐧",
    theme: "--c-cyan",
    age: "3-6 岁",
    tag: "反应·躲避",
  },
  {
    id: "kangaroo-hop",
    title: "袋鼠跳",
    subtitle: "跳过障碍收集袋子",
    icon: "🦘",
    theme: "--c-yellow",
    age: "3-6 岁",
    tag: "反应·跳跃",
  },
  {
    id: "beaver-dam",
    title: "海狸筑坝",
    subtitle: "按图摆木头筑坝",
    icon: "🦫",
    theme: "--c-brown",
    age: "4-6 岁",
    tag: "创造·拼图",
  },
  {
    id: "hedgehog-roll",
    title: "刺猬滚",
    subtitle: "滚动收集果子",
    icon: "🦔",
    theme: "--c-brown",
    age: "3-6 岁",
    tag: "反应·收集",
  },
  {
    id: "chameleon-color",
    title: "变色龙",
    subtitle: "变成和环境一样的色",
    icon: "🦎",
    theme: "--c-green",
    age: "3-6 岁",
    tag: "反应·颜色",
  },
  {
    id: "firefly-catch",
    title: "萤火虫",
    subtitle: "抓亮起的萤火虫",
    icon: "✨",
    theme: "--c-yellow",
    age: "3-6 岁",
    tag: "反应·点击",
  },
  {
    id: "dragonfly-count",
    title: "池塘数数",
    subtitle: "池塘几只小飞虫",
    icon: "🦗",
    theme: "--c-teal",
    age: "3-5 岁",
    tag: "数学·计数",
  },
  {
    id: "caterpillar-grow",
    title: "毛毛虫",
    subtitle: "按顺序吃叶子长大",
    icon: "🐛",
    theme: "--c-green",
    age: "3-6 岁",
    tag: "认知·生长",
  },
  {
    id: "spiral-snail",
    title: "蜗牛螺旋",
    subtitle: "沿螺旋走到中心",
    icon: "🐌",
    theme: "--c-purple",
    age: "4-6 岁",
    tag: "逻辑·路径",
  },
  {
    id: "ant-bridge",
    title: "蚂蚁桥",
    subtitle: "蚂蚁搭桥过沟",
    icon: "🐜",
    theme: "--c-brown",
    age: "4-6 岁",
    tag: "逻辑·策略",
  },
  {
    id: "bee-honey",
    title: "蜂蜜量",
    subtitle: "倒蜂蜜到刻度",
    icon: "🍯",
    theme: "--c-yellow",
    age: "4-6 岁",
    tag: "数学·体积",
  },
  {
    id: "ladybug-spot",
    title: "瓢虫斑",
    subtitle: "数瓢虫有几个斑点",
    icon: "🐞",
    theme: "--c-red",
    age: "3-5 岁",
    tag: "数学·计数",
  },
  {
    id: "butterfly-catch",
    title: "捕蝶网",
    subtitle: "网住指定蝴蝶",
    icon: "🦋",
    theme: "--c-purple",
    age: "3-6 岁",
    tag: "反应·拖拽",
  },
  {
    id: "frog-croak",
    title: "蛙鸣",
    subtitle: "记住蛙叫节奏",
    icon: "🐸",
    theme: "--c-green",
    age: "4-6 岁",
    tag: "记忆·听觉",
  },
  {
    id: "turtle-race",
    title: "龟赛跑2",
    subtitle: "控制乌龟匀速前进",
    icon: "🐢",
    theme: "--c-green",
    age: "3-6 岁",
    tag: "反应·控制",
  },
  {
    id: "fish-bowl",
    title: "鱼缸水",
    subtitle: "加水到目标刻度",
    icon: "🐟",
    theme: "--c-blue",
    age: "4-6 岁",
    tag: "数学·体积",
  },
  {
    id: "bird-nest",
    title: "鸟巢蛋",
    subtitle: "鸟巢里有几颗蛋",
    icon: "🪺",
    theme: "--c-brown",
    age: "3-5 岁",
    tag: "数学·计数",
  },
  {
    id: "squirrel-hide",
    title: "松鼠藏果",
    subtitle: "记住坚果藏哪了",
    icon: "🐿️",
    theme: "--c-brown",
    age: "3-6 岁",
    tag: "记忆·追踪",
  },
  {
    id: "rabbit-burrow",
    title: "兔洞迷宫",
    subtitle: "穿过兔洞找到出口",
    icon: "🐰",
    theme: "--c-pink",
    age: "4-6 岁",
    tag: "逻辑·迷宫",
  },
  {
    id: "bat-cave",
    title: "蝙蝠洞",
    subtitle: "倒挂的蝙蝠找配对",
    icon: "🦇",
    theme: "--c-indigo",
    age: "3-6 岁",
    tag: "认知·配对",
  },
  {
    id: "snake-slither",
    title: "蛇行",
    subtitle: "控制蛇S形前进",
    icon: "🐍",
    theme: "--c-green",
    age: "3-6 岁",
    tag: "反应·控制",
  },
  {
    id: "owl-pellet",
    title: "猫头鹰丸",
    subtitle: "分类丸子里的骨头",
    icon: "🦴",
    theme: "--c-brown",
    age: "4-6 岁",
    tag: "认知·分类",
  },
  {
    id: "mole-vision",
    title: "鼹鼠视野",
    subtitle: "黑暗中找蘑菇",
    icon: "🍄",
    theme: "--c-brown",
    age: "3-6 岁",
    tag: "专注·观察",
  },
  {
    id: "plankton-feed",
    title: "浮游喂",
    subtitle: "喂鲸鱼对的浮游",
    icon: "🐋",
    theme: "--c-blue",
    age: "3-6 岁",
    tag: "认知·配对",
  },
  {
    id: "coral-reef",
    title: "珊瑚礁",
    subtitle: "按颜色排列珊瑚",
    icon: "🪸",
    theme: "--c-pink",
    age: "3-6 岁",
    tag: "认知·排序",
  },
  {
    id: "jellyfish-glow",
    title: "水母光",
    subtitle: "按发光顺序点水母",
    icon: "🪼",
    theme: "--c-purple",
    age: "4-6 岁",
    tag: "记忆·序列",
  },
  {
    id: "sushi-master",
    title: "寿司大师",
    subtitle: "按配方做寿司",
    icon: "🍣",
    theme: "--c-red",
    age: "4-6 岁",
    tag: "认知·配对",
  },
  {
    id: "pizza-chef",
    title: "披萨师",
    subtitle: "照图放对配料",
    icon: "🍕",
    theme: "--c-orange",
    age: "3-6 岁",
    tag: "认知·配对",
  },
  {
    id: "cake-decor",
    title: "蛋糕装饰",
    subtitle: "对称装饰蛋糕",
    icon: "🎂",
    theme: "--c-pink",
    age: "3-6 岁",
    tag: "创造·对称",
  },
  {
    id: "juice-blend",
    title: "果汁调配",
    subtitle: "按比例混合果汁",
    icon: "🧃",
    theme: "--c-orange",
    age: "4-6 岁",
    tag: "数学·比例",
  },
  {
    id: "noodle-pull",
    title: "拉面长短",
    subtitle: "比较面条长短",
    icon: "🍜",
    theme: "--c-yellow",
    age: "3-5 岁",
    tag: "认知·比较",
  },
  {
    id: "dumpling-count",
    title: "饺子数",
    subtitle: "蒸笼里有几只饺子",
    icon: "🥟",
    theme: "--c-orange",
    age: "3-5 岁",
    tag: "数学·计数",
  },
  {
    id: "tea-cup",
    title: "茶杯温度",
    subtitle: "按温度选对的茶",
    icon: "🍵",
    theme: "--c-green",
    age: "4-6 岁",
    tag: "认知·温度",
  },
  {
    id: "cookie-decor",
    title: "饼干装饰",
    subtitle: "按规律装饰饼干",
    icon: "🍪",
    theme: "--c-brown",
    age: "3-6 岁",
    tag: "逻辑·规律",
  },
  {
    id: "pancake-flip",
    title: "煎饼翻",
    subtitle: "时机翻面不焦",
    icon: "🥞",
    theme: "--c-orange",
    age: "3-6 岁",
    tag: "反应·时机",
  },
  {
    id: "popcorn-pop",
    title: "爆米花",
    subtitle: "数爆了几颗",
    icon: "🍿",
    theme: "--c-yellow",
    age: "3-5 岁",
    tag: "数学·计数",
  },
  {
    id: "ice-cream-flavor",
    title: "冰淇淋",
    subtitle: "口味和蛋筒配对",
    icon: "🍦",
    theme: "--c-pink",
    age: "3-6 岁",
    tag: "认知·配对",
  },
  {
    id: "sandwich-stack",
    title: "三明治",
    subtitle: "按顺序叠三明治",
    icon: "🥪",
    theme: "--c-green",
    age: "3-6 岁",
    tag: "记忆·顺序",
  },
  {
    id: "olympic-rings",
    title: "五环",
    subtitle: "按顺序排奥运环",
    icon: "🏵️",
    theme: "--c-blue",
    age: "4-6 岁",
    tag: "认知·顺序",
  },
  {
    id: "medal-count",
    title: "奖牌数",
    subtitle: "数领奖台奖牌",
    icon: "🥇",
    theme: "--c-yellow",
    age: "3-5 岁",
    tag: "数学·计数",
  },
  {
    id: "stadium-cheer",
    title: "观众席",
    subtitle: "找观众席不同",
    icon: "🏟️",
    theme: "--c-green",
    age: "4-6 岁",
    tag: "专注·观察",
  },
  {
    id: "relay-baton",
    title: "接力棒",
    subtitle: "按顺序传接力棒",
    icon: "🏃",
    theme: "--c-orange",
    age: "3-6 岁",
    tag: "记忆·顺序",
  },
  {
    id: "swim-lane",
    title: "泳道",
    subtitle: "按编号找到泳道",
    icon: "🏊",
    theme: "--c-cyan",
    age: "4-6 岁",
    tag: "数学·数序",
  },
  {
    id: "archery-target",
    title: "射箭",
    subtitle: "射中指定环数",
    icon: "🎯",
    theme: "--c-red",
    age: "4-6 岁",
    tag: "反应·瞄准",
  },
  {
    id: "skate-trick",
    title: "滑板",
    subtitle: "按序列做动作",
    icon: "🛹",
    theme: "--c-purple",
    age: "4-6 岁",
    tag: "记忆·序列",
  },
  {
    id: "basketball-hoop",
    title: "投篮",
    subtitle: "按数字投进框",
    icon: "🏀",
    theme: "--c-orange",
    age: "3-6 岁",
    tag: "反应·瞄准",
  },
  {
    id: "soccer-pass",
    title: "传球",
    subtitle: "画出传球路线",
    icon: "⚽",
    theme: "--c-green",
    age: "4-6 岁",
    tag: "逻辑·路径",
  },
  {
    id: "gymnastics-score",
    title: "体操分",
    subtitle: "按表现打分排序",
    icon: "🤸",
    theme: "--c-purple",
    age: "4-6 岁",
    tag: "认知·排序",
  },
  {
    id: "karate-belt",
    title: "腰带",
    subtitle: "按颜色等级排带",
    icon: "🥋",
    theme: "--c-brown",
    age: "4-6 岁",
    tag: "认知·排序",
  },
  {
    id: "flag-raising",
    title: "升旗",
    subtitle: "国旗按高矮排",
    icon: "🚩",
    theme: "--c-red",
    age: "3-6 岁",
    tag: "认知·排序",
  },
  {
    id: "torch-relay",
    title: "火炬接力",
    subtitle: "按城市顺序传火炬",
    icon: "🔥",
    theme: "--c-orange",
    age: "4-6 岁",
    tag: "记忆·顺序",
  },
  {
    id: "dice-roll",
    title: "掷骰",
    subtitle: "数骰子几点",
    icon: "🎲",
    theme: "--c-purple",
    age: "3-5 岁",
    tag: "数学·计数",
  },
  {
    id: "card-deal",
    title: "翻牌比大小",
    subtitle: "翻牌比谁更大",
    icon: "🃏",
    theme: "--c-indigo",
    age: "4-6 岁",
    tag: "数学·比较",
  },
  {
    id: "coin-flip",
    title: "翻硬币",
    subtitle: "猜正面还是反面",
    icon: "🪙",
    theme: "--c-yellow",
    age: "3-6 岁",
    tag: "认知·概率",
  },
  {
    id: "slot-machine",
    title: "拉霸",
    subtitle: "转到相同图案",
    icon: "🎰",
    theme: "--c-red",
    age: "3-6 岁",
    tag: "反应·概率",
  },
  {
    id: "bingo-card",
    title: "宾果",
    subtitle: "找到对应数字格",
    icon: "🎟️",
    theme: "--c-green",
    age: "4-6 岁",
    tag: "数学·数序",
  },
  {
    id: "puzzle-jigsaw-3",
    title: "进阶拼图",
    subtitle: "拼出更复杂的图",
    icon: "🧩",
    theme: "--c-blue",
    age: "4-6 岁",
    tag: "创造·拼图",
  },
  {
    id: "rubik-mini",
    title: "迷你魔方",
    subtitle: "转面让颜色归位",
    icon: "🟦",
    theme: "--c-indigo",
    age: "5-6 岁",
    tag: "逻辑·策略",
  },
  {
    id: "robot-maze",
    title: "机器人迷宫",
    subtitle: "编程走通迷宫",
    icon: "🤖",
    theme: "--c-blue",
    age: "4-6 岁",
    tag: "逻辑·编程",
  },
  {
    id: "satellite-orbit",
    title: "卫星轨道",
    subtitle: "按距离排卫星",
    icon: "🛰️",
    theme: "--c-indigo",
    age: "4-6 岁",
    tag: "科学·天文",
  },
  {
    id: "mars-rover",
    title: "火星车",
    subtitle: "遥控避障收集",
    icon: "🚙",
    theme: "--c-red",
    age: "3-6 岁",
    tag: "反应·控制",
  },
  {
    id: "alien-translate",
    title: "外星语",
    subtitle: "翻译外星符号",
    icon: "👽",
    theme: "--c-green",
    age: "4-6 岁",
    tag: "语言·符号",
  },
  {
    id: "ufo-catch",
    title: "UFO吸物",
    subtitle: "吸起指定物品",
    icon: "🛸",
    theme: "--c-purple",
    age: "3-6 岁",
    tag: "反应·分类",
  },
  {
    id: "asteroid-dodge",
    title: "躲陨石",
    subtitle: "飞船躲开陨石",
    icon: "☄️",
    theme: "--c-red",
    age: "3-6 岁",
    tag: "反应·躲避",
  },
  {
    id: "space-dock",
    title: "空间站",
    subtitle: "对接飞船到端口",
    icon: "🏛️",
    theme: "--c-cyan",
    age: "4-6 岁",
    tag: "逻辑·配对",
  },
  {
    id: "black-hole",
    title: "黑洞",
    subtitle: "吸走指定颜色星球",
    icon: "🕳️",
    theme: "--c-indigo",
    age: "3-6 岁",
    tag: "反应·颜色",
  },
  {
    id: "meteor-shower",
    title: "流星雨",
    subtitle: "接住流星碎片",
    icon: "🌟",
    theme: "--c-yellow",
    age: "3-6 岁",
    tag: "反应·接物",
  },
  {
    id: "gravity-well",
    title: "引力井",
    subtitle: "弹射球到目标",
    icon: "🌀",
    theme: "--c-purple",
    age: "4-6 岁",
    tag: "逻辑·物理",
  },
  {
    id: "crystal-mine",
    title: "水晶矿",
    subtitle: "按颜色分拣水晶",
    icon: "💎",
    theme: "--c-cyan",
    age: "3-6 岁",
    tag: "认知·分类",
  },
  {
    id: "dragon-treasure",
    title: "龙宝藏",
    subtitle: "按价值排宝物",
    icon: "🐉",
    theme: "--c-red",
    age: "4-6 岁",
    tag: "认知·排序",
  },
  {
    id: "wizard-potion",
    title: "巫师药水",
    subtitle: "按配方调药水",
    icon: "🧙",
    theme: "--c-purple",
    age: "4-6 岁",
    tag: "认知·颜色",
  },
  {
    id: "fairy-dust",
    title: "仙粉",
    subtitle: "撒对应色的仙粉",
    icon: "🧚",
    theme: "--c-pink",
    age: "3-6 岁",
    tag: "认知·颜色",
  },
  {
    id: "knight-shield",
    title: "骑士盾",
    subtitle: "配对盾牌纹样",
    icon: "🛡️",
    theme: "--c-blue",
    age: "3-6 岁",
    tag: "认知·配对",
  },
  {
    id: "castle-gate",
    title: "城堡门",
    subtitle: "输入密码开门",
    icon: "🏰",
    theme: "--c-brown",
    age: "4-6 岁",
    tag: "记忆·序列",
  },
  {
    id: "mermaid-pearl",
    title: "美人鱼",
    subtitle: "按规律串珍珠",
    icon: "🧜",
    theme: "--c-cyan",
    age: "4-6 岁",
    tag: "逻辑·规律",
  },
  {
    id: "phoenix-feather",
    title: "凤凰羽",
    subtitle: "按热度排羽毛",
    icon: "🔥",
    theme: "--c-orange",
    age: "4-6 岁",
    tag: "认知·排序",
  },
  {
    id: "unicorn-horn",
    title: "独角兽",
    subtitle: "角的颜色配对",
    icon: "🦄",
    theme: "--c-pink",
    age: "3-6 岁",
    tag: "认知·配对",
  },
  {
    id: "elf-bow",
    title: "精灵弓",
    subtitle: "射中目标靶心",
    icon: "🏹",
    theme: "--c-green",
    age: "3-6 岁",
    tag: "反应·瞄准",
  },
  {
    id: "troll-bridge",
    title: "巨魔桥",
    subtitle: "答对才能过桥",
    icon: "👹",
    theme: "--c-brown",
    age: "4-6 岁",
    tag: "认知·问答",
  },
  {
    id: "ghost-castle",
    title: "鬼城堡",
    subtitle: "记住鬼出现位置",
    icon: "👻",
    theme: "--c-purple",
    age: "4-6 岁",
    tag: "记忆·观察",
  },
  {
    id: "vampire-bat",
    title: "吸血蝠",
    subtitle: "避光走出洞穴",
    icon: "🦇",
    theme: "--c-indigo",
    age: "3-6 岁",
    tag: "反应·躲避",
  },
  {
    id: "werewolf-shadow",
    title: "狼人影",
    subtitle: "踩影子追逃",
    icon: "🐺",
    theme: "--c-brown",
    age: "3-6 岁",
    tag: "反应·追逐",
  },
  {
    id: "zombie-garden",
    title: "僵尸园",
    subtitle: "种花驱赶僵尸",
    icon: "🧟",
    theme: "--c-green",
    age: "3-6 岁",
    tag: "反应·策略",
  },
  {
    id: "pumpkin-carve",
    title: "南瓜刻",
    subtitle: "对称雕刻南瓜",
    icon: "🎃",
    theme: "--c-orange",
    age: "4-6 岁",
    tag: "创造·对称",
  },
  {
    id: "haunted-mirror",
    title: "鬼镜",
    subtitle: "镜中找不同",
    icon: "🪞",
    theme: "--c-purple",
    age: "4-6 岁",
    tag: "专注·观察",
  },
  {
    id: "spell-circle",
    title: "魔法阵",
    subtitle: "按顺序连线激活",
    icon: "🔮",
    theme: "--c-indigo",
    age: "4-6 岁",
    tag: "记忆·序列",
  },
  {
    id: "potion-brew",
    title: "魔药",
    subtitle: "按顺序加材料",
    icon: "⚗️",
    theme: "--c-green",
    age: "4-6 岁",
    tag: "记忆·顺序",
  },
  {
    id: "magic-wand",
    title: "魔棒",
    subtitle: "点对颜色施法",
    icon: "🪄",
    theme: "--c-purple",
    age: "3-6 岁",
    tag: "反应·颜色",
  },
  {
    id: "crystal-ball",
    title: "水晶球",
    subtitle: "预测下一个图案",
    icon: "🔮",
    theme: "--c-blue",
    age: "4-6 岁",
    tag: "逻辑·规律",
  },
  {
    id: "enchantment",
    title: "附魔",
    subtitle: "颜色匹配附魔",
    icon: "✨",
    theme: "--c-pink",
    age: "3-6 岁",
    tag: "认知·配对",
  },
  {
    id: "listen-act",
    title: "听指令",
    subtitle: "听声音做对应动作",
    icon: "👂",
    theme: "--c-blue",
    age: "3-5 岁",
    tag: "语言·听说",
  },
  {
    id: "story-order",
    title: "故事排序",
    subtitle: "按时间排故事图卡",
    icon: "📖",
    theme: "--c-indigo",
    age: "4-6 岁",
    tag: "语言·叙事",
  },
  {
    id: "rhyme-fill",
    title: "儿歌填词",
    subtitle: "补全儿歌缺的词",
    icon: "🎵",
    theme: "--c-pink",
    age: "4-5 岁",
    tag: "语言·韵律",
  },
  {
    id: "picture-talk",
    title: "看图说话",
    subtitle: "选正确的描述句",
    icon: "🖼️",
    theme: "--c-teal",
    age: "4-5 岁",
    tag: "语言·表达",
  },
  {
    id: "tongue-twist",
    title: "绕口令",
    subtitle: "听绕口令选对字",
    icon: "🗣️",
    theme: "--c-purple",
    age: "5-6 岁",
    tag: "语言·语音",
  },
  {
    id: "upper-lower",
    title: "大小写",
    subtitle: "大写字母配小写",
    icon: "🔤",
    theme: "--c-blue",
    age: "4-5 岁",
    tag: "语言·字母",
  },
  {
    id: "sentence-build",
    title: "拼句子",
    subtitle: "词卡拼成完整句",
    icon: "📝",
    theme: "--c-indigo",
    age: "5-6 岁",
    tag: "语言·阅读",
  },
  {
    id: "opposite-match",
    title: "反义词",
    subtitle: "意思相反的词配对",
    icon: "⚖️",
    theme: "--c-purple",
    age: "4-6 岁",
    tag: "语言·词汇",
  },
  {
    id: "describe-pic",
    title: "描述图",
    subtitle: "选最准确的描述",
    icon: "👁️",
    theme: "--c-teal",
    age: "5-6 岁",
    tag: "语言·表达",
  },
  {
    id: "question-answer",
    title: "问答",
    subtitle: "看情景回答问题",
    icon: "❓",
    theme: "--c-orange",
    age: "5-6 岁",
    tag: "语言·理解",
  },
  {
    id: "sound-letter",
    title: "字母音",
    subtitle: "听字母发音选字母",
    icon: "🔊",
    theme: "--c-blue",
    age: "4-5 岁",
    tag: "语言·语音",
  },
  {
    id: "category-name",
    title: "归类",
    subtitle: "说出同类的名称",
    icon: "🗂️",
    theme: "--c-green",
    age: "4-5 岁",
    tag: "语言·概念",
  },
  {
    id: "find-mistake",
    title: "找语病",
    subtitle: "判断句子对不对",
    icon: "🔍",
    theme: "--c-red",
    age: "5-6 岁",
    tag: "语言·逻辑",
  },
  {
    id: "sequence-word",
    title: "词排序",
    subtitle: "按正确顺序排词语",
    icon: "📋",
    theme: "--c-indigo",
    age: "4-5 岁",
    tag: "语言·时序",
  },
  {
    id: "story-end",
    title: "故事结局",
    subtitle: "选合理的结局",
    icon: "📕",
    theme: "--c-purple",
    age: "5-6 岁",
    tag: "语言·推理",
  },
  {
    id: "share-toy",
    title: "分享",
    subtitle: "选正确的分享做法",
    icon: "🤝",
    theme: "--c-pink",
    age: "3-4 岁",
    tag: "社交·分享",
  },
  {
    id: "queue-up",
    title: "排队",
    subtitle: "判断排队对不对",
    icon: "🚶",
    theme: "--c-blue",
    age: "3-4 岁",
    tag: "社交·规则",
  },
  {
    id: "coop-build",
    title: "合作搭",
    subtitle: "轮流放积木搭目标",
    icon: "🏗️",
    theme: "--c-green",
    age: "4-5 岁",
    tag: "社交·合作",
  },
  {
    id: "say-sorry",
    title: "道歉",
    subtitle: "选正确的道歉方式",
    icon: "🙏",
    theme: "--c-yellow",
    age: "4-5 岁",
    tag: "社交·礼仪",
  },
  {
    id: "greeting",
    title: "打招呼",
    subtitle: "选正确的问候语",
    icon: "👋",
    theme: "--c-teal",
    age: "3-4 岁",
    tag: "社交·礼仪",
  },
  {
    id: "take-turns",
    title: "轮流",
    subtitle: "判断谁该轮到了",
    icon: "🔄",
    theme: "--c-orange",
    age: "4-5 岁",
    tag: "社交·规则",
  },
  {
    id: "resolve-fight",
    title: "和解",
    subtitle: "选最好的解决办法",
    icon: "☮️",
    theme: "--c-purple",
    age: "5-6 岁",
    tag: "社交·冲突",
  },
  {
    id: "help-others",
    title: "帮助人",
    subtitle: "选正确的帮助方式",
    icon: "💕",
    theme: "--c-red",
    age: "4-5 岁",
    tag: "社交·同理",
  },
  {
    id: "team-task",
    title: "团队",
    subtitle: "分配角色完成任务",
    icon: "👫",
    theme: "--c-blue",
    age: "5-6 岁",
    tag: "社交·合作",
  },
  {
    id: "mood-read",
    title: "读心",
    subtitle: "看表情判断心情",
    icon: "😊",
    theme: "--c-pink",
    age: "4-5 岁",
    tag: "社交·情感",
  },
  {
    id: "warm-cool",
    title: "冷暖色",
    subtitle: "把颜色分暖色冷色",
    icon: "🌡️",
    theme: "--c-orange",
    age: "3-5 岁",
    tag: "艺术·色彩",
  },
  {
    id: "beat-clap",
    title: "打节拍",
    subtitle: "跟着节拍点击",
    icon: "👏",
    theme: "--c-purple",
    age: "3-5 岁",
    tag: "艺术·节奏",
  },
  {
    id: "instrument",
    title: "辨乐器",
    subtitle: "听声音选乐器",
    icon: "🎺",
    theme: "--c-yellow",
    age: "4-6 岁",
    tag: "艺术·音色",
  },
  {
    id: "finger-paint",
    title: "手指画",
    subtitle: "手指涂抹自由画画",
    icon: "🎨",
    theme: "--c-pink",
    age: "3-5 岁",
    tag: "艺术·触觉",
  },
  {
    id: "origami-2",
    title: "折纸2",
    subtitle: "复杂折纸步骤排序",
    icon: "📄",
    theme: "--c-teal",
    age: "4-6 岁",
    tag: "艺术·空间",
  },
  {
    id: "dance-copy",
    title: "跳舞",
    subtitle: "按顺序模仿动作",
    icon: "💃",
    theme: "--c-red",
    age: "3-5 岁",
    tag: "艺术·身体",
  },
  {
    id: "color-fill",
    title: "涂色",
    subtitle: "给线稿填色",
    icon: "🖍️",
    theme: "--c-cyan",
    age: "3-6 岁",
    tag: "艺术·填色",
  },
  {
    id: "pattern-design",
    title: "图案",
    subtitle: "设计重复图案",
    icon: "🔷",
    theme: "--c-indigo",
    age: "4-6 岁",
    tag: "艺术·创造",
  },
  {
    id: "music-mood",
    title: "音乐感",
    subtitle: "听音乐选情绪",
    icon: "🎼",
    theme: "--c-purple",
    age: "4-6 岁",
    tag: "艺术·情感",
  },
  {
    id: "paper-cut",
    title: "剪纸",
    subtitle: "按虚线剪出图案",
    icon: "✂️",
    theme: "--c-red",
    age: "5-6 岁",
    tag: "艺术·传统",
  },
  {
    id: "lace-board",
    title: "穿线板",
    subtitle: "沿孔洞穿绳",
    icon: "🧵",
    theme: "--c-pink",
    age: "3-4 岁",
    tag: "精细·穿绳",
  },
  {
    id: "pick-beans",
    title: "夹豆子",
    subtitle: "夹指定颜色豆子",
    icon: "🥢",
    theme: "--c-green",
    age: "4-5 岁",
    tag: "精细·筷子",
  },
  {
    id: "cut-line",
    title: "剪线条",
    subtitle: "沿虚线剪开",
    icon: "✂️",
    theme: "--c-teal",
    age: "4-5 岁",
    tag: "精细·剪刀",
  },
  {
    id: "tie-shoe",
    title: "系鞋带",
    subtitle: "按步骤系鞋带",
    icon: "👟",
    theme: "--c-blue",
    age: "5-6 岁",
    tag: "精细·打结",
  },
  {
    id: "zipper-pull",
    title: "拉链",
    subtitle: "拖拉链头到顶",
    icon: "🧥",
    theme: "--c-orange",
    age: "3-4 岁",
    tag: "精细·拉拽",
  },
  {
    id: "button-press",
    title: "纽扣",
    subtitle: "按纽扣进扣眼",
    icon: "🔘",
    theme: "--c-yellow",
    age: "3-4 岁",
    tag: "精细·捏按",
  },
  {
    id: "tear-paste",
    title: "撕贴画",
    subtitle: "撕纸贴到轮廓",
    icon: "📄",
    theme: "--c-purple",
    age: "3-4 岁",
    tag: "精细·撕贴",
  },
  {
    id: "bead-string",
    title: "串珠",
    subtitle: "按规律串珠子",
    icon: "📿",
    theme: "--c-cyan",
    age: "3-4 岁",
    tag: "精细·串珠",
  },
  {
    id: "brush-teeth",
    title: "刷牙",
    subtitle: "刷牙步骤排序",
    icon: "🪥",
    theme: "--c-cyan",
    age: "3-4 岁",
    tag: "生活·卫生",
  },
  {
    id: "wash-hands",
    title: "洗手",
    subtitle: "洗手七步排序",
    icon: "🧼",
    theme: "--c-blue",
    age: "3-4 岁",
    tag: "生活·卫生",
  },
  {
    id: "dress-order",
    title: "穿衣",
    subtitle: "穿衣正确顺序",
    icon: "👕",
    theme: "--c-pink",
    age: "4-5 岁",
    tag: "生活·穿衣",
  },
  {
    id: "cross-road",
    title: "过马路",
    subtitle: "看红绿灯过马路",
    icon: "🚦",
    theme: "--c-red",
    age: "4-5 岁",
    tag: "生活·安全",
  },
  {
    id: "stranger",
    title: "防生人",
    subtitle: "陌生人给东西怎么办",
    icon: "🚫",
    theme: "--c-indigo",
    age: "4-5 岁",
    tag: "生活·安全",
  },
  {
    id: "healthy-eat",
    title: "健康吃",
    subtitle: "分健康和不健康食物",
    icon: "🥗",
    theme: "--c-green",
    age: "4-5 岁",
    tag: "生活·营养",
  },
  {
    id: "pack-bag",
    title: "收书包",
    subtitle: "按课表选书装包",
    icon: "🎒",
    theme: "--c-orange",
    age: "5-6 岁",
    tag: "生活·整理",
  },
  {
    id: "tidy-room",
    title: "收拾2",
    subtitle: "更多类别整理房间",
    icon: "🧹",
    theme: "--c-brown",
    age: "4-5 岁",
    tag: "生活·整理",
  },
  {
    id: "world-landmark",
    title: "世界地标",
    subtitle: "地标配对国家",
    icon: "🗼",
    theme: "--c-indigo",
    age: "4-6 岁",
    tag: "科学·地理",
  },
  {
    id: "flag-match",
    title: "国旗",
    subtitle: "国旗配大洲",
    icon: "🏳️",
    theme: "--c-red",
    age: "5-6 岁",
    tag: "科学·地理",
  },
  {
    id: "currency-world",
    title: "各国钱",
    subtitle: "认识不同货币",
    icon: "💱",
    theme: "--c-green",
    age: "5-6 岁",
    tag: "数学·货币",
  },
  {
    id: "hello-world",
    title: "世界你好",
    subtitle: "各国语言问候",
    icon: "🌍",
    theme: "--c-blue",
    age: "4-6 岁",
    tag: "语言·文化",
  },
  {
    id: "food-world",
    title: "世界美食",
    subtitle: "美食配国家",
    icon: "🍜",
    theme: "--c-orange",
    age: "4-6 岁",
    tag: "认知·文化",
  },
  {
    id: "animal-continent",
    title: "动物家",
    subtitle: "动物住在哪个洲",
    icon: "🗺️",
    theme: "--c-green",
    age: "4-6 岁",
    tag: "科学·地理",
  },
  {
    id: "season-nature",
    title: "季节自然",
    subtitle: "季节配自然现象",
    icon: "🍂",
    theme: "--c-teal",
    age: "4-6 岁",
    tag: "科学·自然",
  },
  {
    id: "weather-type",
    title: "天气类型",
    subtitle: "认识不同天气",
    icon: "🌦️",
    theme: "--c-cyan",
    age: "3-5 岁",
    tag: "认知·天气",
  },
  {
    id: "plant-grow",
    title: "植物生长",
    subtitle: "排出植物生长顺序",
    icon: "🌱",
    theme: "--c-green",
    age: "3-6 岁",
    tag: "科学·生物",
  },
  {
    id: "rock-cycle",
    title: "岩石循环",
    subtitle: "岩石的变化顺序",
    icon: "🪨",
    theme: "--c-brown",
    age: "5-6 岁",
    tag: "科学·地质",
  },
  {
    id: "water-cycle",
    title: "水循环",
    subtitle: "排出水循环过程",
    icon: "💧",
    theme: "--c-blue",
    age: "4-6 岁",
    tag: "科学·自然",
  },
  {
    id: "food-chain-2",
    title: "食物链2",
    subtitle: "更多食物链配对",
    icon: "🦁",
    theme: "--c-green",
    age: "5-6 岁",
    tag: "科学·生态",
  },
  {
    id: "body-parts",
    title: "身体部位",
    subtitle: "认识身体各部位",
    icon: "🧍",
    theme: "--c-pink",
    age: "3-5 岁",
    tag: "认知·身体",
  },
  {
    id: "five-senses",
    title: "五官",
    subtitle: "五官认识与功能",
    icon: "👁️",
    theme: "--c-purple",
    age: "3-5 岁",
    tag: "认知·身体",
  },
  {
    id: "healthy-habit",
    title: "好习惯",
    subtitle: "选出健康好习惯",
    icon: "💪",
    theme: "--c-green",
    age: "3-6 岁",
    tag: "生活·健康",
  },
  {
    id: "emotion-cope",
    title: "情绪应对",
    subtitle: "选正确的应对方式",
    icon: "🤗",
    theme: "--c-pink",
    age: "4-6 岁",
    tag: "社交·情感",
  },
  {
    id: "color-feeling",
    title: "颜色情绪",
    subtitle: "颜色与情绪配对",
    icon: "🎭",
    theme: "--c-purple",
    age: "4-6 岁",
    tag: "艺术·情感",
  },
  {
    id: "music-speed",
    title: "快慢音",
    subtitle: "辨别音乐快慢",
    icon: "🎚️",
    theme: "--c-yellow",
    age: "3-6 岁",
    tag: "艺术·音乐",
  },
  {
    id: "rhythm-copy",
    title: "节奏模仿2",
    subtitle: "更多节奏序列",
    icon: "🥁",
    theme: "--c-red",
    age: "4-6 岁",
    tag: "记忆·听觉",
  },
  {
    id: "story-moral",
    title: "故事道理",
    subtitle: "选故事的道理",
    icon: "📚",
    theme: "--c-indigo",
    age: "5-6 岁",
    tag: "语言·理解",
  },
  {
    id: "fairytale",
    title: "童话",
    subtitle: "童话角色配对",
    icon: "🏰",
    theme: "--c-purple",
    age: "3-6 岁",
    tag: "认知·配对",
  },
  {
    id: "count-song",
    title: "数数歌",
    subtitle: "儿歌里数到几",
    icon: "🎶",
    theme: "--c-yellow",
    age: "3-5 岁",
    tag: "数学·计数",
  },
  {
    id: "shape-hunt",
    title: "形状搜寻",
    subtitle: "找出所有某形状",
    icon: "🔍",
    theme: "--c-teal",
    age: "3-5 岁",
    tag: "认知·形状",
  },
  {
    id: "mirror-word",
    title: "镜像字",
    subtitle: "找出镜像翻转的字",
    icon: "🪞",
    theme: "--c-indigo",
    age: "5-6 岁",
    tag: "认知·空间",
  },
  {
    id: "letter-trace",
    title: "字母描红",
    subtitle: "沿虚线描字母",
    icon: "✏️",
    theme: "--c-blue",
    age: "4-5 岁",
    tag: "精细·书写",
  },
  {
    id: "number-trace",
    title: "数字描红",
    subtitle: "沿虚线描数字",
    icon: "🔢",
    theme: "--c-green",
    age: "4-5 岁",
    tag: "精细·书写",
  },
  {
    id: "color-name",
    title: "认颜色",
    subtitle: "颜色与名字配对",
    icon: "🎨",
    theme: "--c-pink",
    age: "3-4 岁",
    tag: "语言·词汇",
  },
  {
    id: "shape-name",
    title: "认形状",
    subtitle: "形状与名字配对",
    icon: "⭐",
    theme: "--c-orange",
    age: "3-4 岁",
    tag: "语言·词汇",
  },
  {
    id: "opposite-act",
    title: "相反动作",
    subtitle: "做相反的动作",
    icon: "↔️",
    theme: "--c-teal",
    age: "4-6 岁",
    tag: "认知·逆向",
  },
  {
    id: "same-different",
    title: "同与异",
    subtitle: "找出相同和不同",
    icon: "🔄",
    theme: "--c-purple",
    age: "3-5 岁",
    tag: "认知·观察",
  },
  {
    id: "before-after",
    title: "前后",
    subtitle: "排出前后顺序",
    icon: "➡️",
    theme: "--c-blue",
    age: "3-5 岁",
    tag: "认知·顺序",
  },
  {
    id: "part-whole",
    title: "部分整体",
    subtitle: "部分与整体配对",
    icon: "🧩",
    theme: "--c-green",
    age: "3-5 岁",
    tag: "认知·整体",
  },
  {
    id: "play-date",
    title: "约朋友",
    subtitle: "约朋友玩的礼仪",
    icon: "👫",
    theme: "--c-pink",
    age: "3-5 岁",
    tag: "社交·友谊",
  },
  {
    id: "birthday-party",
    title: "生日会",
    subtitle: "生日派对礼仪",
    icon: "🎂",
    theme: "--c-yellow",
    age: "3-6 岁",
    tag: "社交·礼仪",
  },
  {
    id: "lost-found",
    title: "丢东西",
    subtitle: "丢了东西怎么办",
    icon: "🔍",
    theme: "--c-blue",
    age: "4-6 岁",
    tag: "社交·应对",
  },
  {
    id: "good-listener",
    title: "好听众",
    subtitle: "别人说话好好听",
    icon: "👂",
    theme: "--c-teal",
    age: "3-5 岁",
    tag: "社交·礼仪",
  },
  {
    id: "please-thanks",
    title: "请谢谢",
    subtitle: "用对礼貌用语",
    icon: "🙏",
    theme: "--c-pink",
    age: "3-4 岁",
    tag: "社交·礼仪",
  },
  {
    id: "wait-patient",
    title: "耐心等",
    subtitle: "什么时候要等待",
    icon: "⏰",
    theme: "--c-orange",
    age: "3-5 岁",
    tag: "社交·规则",
  },
  {
    id: "share-snack",
    title: "分零食",
    subtitle: "和好朋友分零食",
    icon: "🍪",
    theme: "--c-brown",
    age: "3-4 岁",
    tag: "社交·分享",
  },
  {
    id: "comfort-friend",
    title: "安慰人",
    subtitle: "朋友难过怎么安慰",
    icon: "🤗",
    theme: "--c-purple",
    age: "4-6 岁",
    tag: "社交·同理",
  },
  {
    id: "table-manners",
    title: "餐桌礼",
    subtitle: "吃饭的好习惯",
    icon: "🍽️",
    theme: "--c-green",
    age: "3-5 岁",
    tag: "生活·礼仪",
  },
  {
    id: "public-rules",
    title: "公共场所",
    subtitle: "公共场所的规则",
    icon: "🏛️",
    theme: "--c-indigo",
    age: "4-6 岁",
    tag: "社交·规则",
  },
  {
    id: "tie-bow",
    title: "蝴蝶结",
    subtitle: "学打蝴蝶结",
    icon: "🎀",
    theme: "--c-pink",
    age: "5-6 岁",
    tag: "精细·打结",
  },
  {
    id: "screw-cap",
    title: "拧盖子",
    subtitle: "拧开和拧紧瓶盖",
    icon: "🫙",
    theme: "--c-cyan",
    age: "3-4 岁",
    tag: "精细·旋转",
  },
  {
    id: "fold-paper-2",
    title: "折纸精细",
    subtitle: "精细折纸练习",
    icon: "📃",
    theme: "--c-teal",
    age: "4-5 岁",
    tag: "精细·折叠",
  },
  {
    id: "peel-sticker",
    title: "撕贴纸",
    subtitle: "撕下贴纸贴好",
    icon: "🏷️",
    theme: "--c-yellow",
    age: "3-4 岁",
    tag: "精细·撕贴",
  },
  {
    id: "insert-key",
    title: "钥匙",
    subtitle: "钥匙插进锁孔",
    icon: "🔑",
    theme: "--c-orange",
    age: "4-5 岁",
    tag: "精细·对准",
  },
  {
    id: "thread-needle",
    title: "穿线",
    subtitle: "线穿进小孔",
    icon: "🪡",
    theme: "--c-purple",
    age: "4-5 岁",
    tag: "精细·穿线",
  },
  {
    id: "open-box",
    title: "开盒子",
    subtitle: "打开不同盖子",
    icon: "📦",
    theme: "--c-brown",
    age: "3-4 岁",
    tag: "精细·开合",
  },
  {
    id: "stack-coins",
    title: "叠硬币",
    subtitle: "精确叠放硬币",
    icon: "🪙",
    theme: "--c-yellow",
    age: "4-5 岁",
    tag: "精细·堆叠",
  },
  {
    id: "tie-hair",
    title: "扎头发",
    subtitle: "用皮筋扎头发",
    icon: "👧",
    theme: "--c-pink",
    age: "5-6 岁",
    tag: "精细·缠绕",
  },
  {
    id: "button-shirt",
    title: "扣衬衫",
    subtitle: "扣好衬衫纽扣",
    icon: "👔",
    theme: "--c-blue",
    age: "4-5 岁",
    tag: "精细·扣扣",
  },
  {
    id: "bath-steps",
    title: "洗澡",
    subtitle: "洗澡正确步骤",
    icon: "🛁",
    theme: "--c-cyan",
    age: "3-4 岁",
    tag: "生活·卫生",
  },
  {
    id: "sleep-routine",
    title: "睡前",
    subtitle: "睡前准备步骤",
    icon: "🛏️",
    theme: "--c-indigo",
    age: "3-5 岁",
    tag: "生活·作息",
  },
  {
    id: "wake-up",
    title: "起床",
    subtitle: "起床后该做什么",
    icon: "⏰",
    theme: "--c-yellow",
    age: "3-5 岁",
    tag: "生活·作息",
  },
  {
    id: "table-setting",
    title: "摆餐具",
    subtitle: "饭前摆好碗筷",
    icon: "🥢",
    theme: "--c-green",
    age: "4-5 岁",
    tag: "生活·家务",
  },
  {
    id: "sort-trash",
    title: "垃圾分类2",
    subtitle: "更多垃圾分类",
    icon: "🗑️",
    theme: "--c-green",
    age: "4-6 岁",
    tag: "生活·环保",
  },
  {
    id: "kitchen-safety",
    title: "厨房安全",
    subtitle: "厨房里的危险",
    icon: "🔥",
    theme: "--c-red",
    age: "4-6 岁",
    tag: "生活·安全",
  },
  {
    id: "medicine-safety",
    title: "用药安全",
    subtitle: "药不能随便吃",
    icon: "💊",
    theme: "--c-red",
    age: "4-6 岁",
    tag: "生活·安全",
  },
  {
    id: "fire-safety",
    title: "消防安全",
    subtitle: "遇到火灾怎么办",
    icon: "🚒",
    theme: "--c-red",
    age: "4-6 岁",
    tag: "生活·安全",
  },
  {
    id: "water-safety",
    title: "水边安全",
    subtitle: "玩水的安全规则",
    icon: "🏊",
    theme: "--c-blue",
    age: "4-6 岁",
    tag: "生活·安全",
  },
  {
    id: "traffic-sign",
    title: "交通标志",
    subtitle: "认识交通标志",
    icon: "🚸",
    theme: "--c-orange",
    age: "4-6 岁",
    tag: "生活·安全",
  },
  {
    id: "emergency-call",
    title: "紧急电话",
    subtitle: "110/119/120认识",
    icon: "📞",
    theme: "--c-red",
    age: "5-6 岁",
    tag: "生活·安全",
  },
  {
    id: "sun-safety",
    title: "防晒",
    subtitle: "防晒防暑好习惯",
    icon: "☀️",
    theme: "--c-orange",
    age: "3-6 岁",
    tag: "生活·健康",
  },
  {
    id: "bird-watch",
    title: "观鸟",
    subtitle: "辨认常见鸟类",
    icon: "🐦",
    theme: "--c-green",
    age: "3-6 岁",
    tag: "科学·自然",
  },
  {
    id: "leaf-id",
    title: "树叶",
    subtitle: "辨认树叶形状",
    icon: "🍃",
    theme: "--c-green",
    age: "4-6 岁",
    tag: "科学·自然",
  },
  {
    id: "flower-type",
    title: "花朵",
    subtitle: "认识花的种类",
    icon: "🌸",
    theme: "--c-pink",
    age: "3-6 岁",
    tag: "科学·自然",
  },
  {
    id: "rock-id",
    title: "石头",
    subtitle: "辨认岩石种类",
    icon: "🪨",
    theme: "--c-brown",
    age: "5-6 岁",
    tag: "科学·地质",
  },
  {
    id: "cloud-type",
    title: "云朵",
    subtitle: "认识云的类型",
    icon: "☁️",
    theme: "--c-blue",
    age: "4-6 岁",
    tag: "科学·气象",
  },
  {
    id: "insect-id",
    title: "昆虫",
    subtitle: "辨认常见昆虫",
    icon: "🐞",
    theme: "--c-green",
    age: "3-6 岁",
    tag: "科学·生物",
  },
  {
    id: "tree-type",
    title: "树木",
    subtitle: "认识树的种类",
    icon: "🌳",
    theme: "--c-green",
    age: "4-6 岁",
    tag: "科学·自然",
  },
  {
    id: "mushroom-id",
    title: "蘑菇",
    subtitle: "辨别蘑菇好坏",
    icon: "🍄",
    theme: "--c-red",
    age: "4-6 岁",
    tag: "科学·生物",
  },
  {
    id: "fruit-tree",
    title: "水果树",
    subtitle: "水果长在什么地方",
    icon: "🍎",
    theme: "--c-orange",
    age: "3-5 岁",
    tag: "科学·自然",
  },
  {
    id: "animal-track",
    title: "脚印",
    subtitle: "辨认动物脚印",
    icon: "🐾",
    theme: "--c-brown",
    age: "4-6 岁",
    tag: "科学·生物",
  },
  {
    id: "scale-piano",
    title: "音阶",
    subtitle: "弹奏C大调音阶",
    icon: "🎹",
    theme: "--c-purple",
    age: "4-6 岁",
    tag: "艺术·音乐",
  },
  {
    id: "chord-match",
    title: "和弦",
    subtitle: "配对和谐的和弦",
    icon: "🎶",
    theme: "--c-indigo",
    age: "5-6 岁",
    tag: "艺术·音乐",
  },
  {
    id: "tempo-game",
    title: "节拍",
    subtitle: "辨别快慢节拍",
    icon: "⏱️",
    theme: "--c-yellow",
    age: "3-6 岁",
    tag: "艺术·节奏",
  },
  {
    id: "scale-up",
    title: "上行",
    subtitle: "按音阶从低到高弹",
    icon: "📈",
    theme: "--c-blue",
    age: "4-6 岁",
    tag: "艺术·音乐",
  },
  {
    id: "scale-down",
    title: "下行",
    subtitle: "按音阶从高到低弹",
    icon: "📉",
    theme: "--c-teal",
    age: "4-6 岁",
    tag: "艺术·音乐",
  },
  {
    id: "echo-song",
    title: "回声",
    subtitle: "听完再唱一遍",
    icon: "🎤",
    theme: "--c-pink",
    age: "4-6 岁",
    tag: "艺术·演唱",
  },
  {
    id: "drum-pattern",
    title: "鼓花样",
    subtitle: "创造鼓点节奏",
    icon: "🥁",
    theme: "--c-red",
    age: "4-6 岁",
    tag: "艺术·节奏",
  },
  {
    id: "sudoku-shape",
    title: "形状数独",
    subtitle: "用形状填数独",
    icon: "🔲",
    theme: "--c-purple",
    age: "5-6 岁",
    tag: "逻辑·推理",
  },
  {
    id: "logic-grid",
    title: "逻辑格",
    subtitle: "根据线索填格子",
    icon: "🔍",
    theme: "--c-indigo",
    age: "5-6 岁",
    tag: "逻辑·推理",
  },
  {
    id: "pattern-3d",
    title: "3D规律",
    subtitle: "立体图形找规律",
    icon: "🎲",
    theme: "--c-blue",
    age: "5-6 岁",
    tag: "逻辑·规律",
  },
  {
    id: "number-cross",
    title: "数字十字",
    subtitle: "横竖都不重复",
    icon: "🔟",
    theme: "--c-teal",
    age: "5-6 岁",
    tag: "数学·逻辑",
  },
  {
    id: "color-sudoku",
    title: "颜色数独",
    subtitle: "用颜色填数独",
    icon: "🌈",
    theme: "--c-pink",
    age: "4-6 岁",
    tag: "逻辑·推理",
  },
  {
    id: "maze-3d",
    title: "3D迷宫",
    subtitle: "立体迷宫找出口",
    icon: "🧊",
    theme: "--c-cyan",
    age: "5-6 岁",
    tag: "逻辑·空间",
  },
  {
    id: "balance-puzzle",
    title: "平衡谜",
    subtitle: "让两边一样重",
    icon: "⚖️",
    theme: "--c-orange",
    age: "4-6 岁",
    tag: "数学·平衡",
  },
  {
    id: "jump-rope",
    title: "跳绳",
    subtitle: "跟着节奏跳绳",
    icon: "🪢",
    theme: "--c-pink",
    age: "3-6 岁",
    tag: "反应·节奏",
  },
  {
    id: "balance-beam",
    title: "平衡木",
    subtitle: "保持平衡不掉下",
    icon: "🤸",
    theme: "--c-blue",
    age: "3-6 岁",
    tag: "反应·平衡",
  },
  {
    id: "ball-catch",
    title: "接球",
    subtitle: "接住抛来的球",
    icon: "⚾",
    theme: "--c-green",
    age: "3-6 岁",
    tag: "反应·接物",
  },
  {
    id: "hula-hoop",
    title: "呼啦圈",
    subtitle: "跟着节奏转圈",
    icon: "🔴",
    theme: "--c-orange",
    age: "4-6 岁",
    tag: "反应·节奏",
  },
  {
    id: "obstacle-run",
    title: "障碍跑",
    subtitle: "躲过所有障碍",
    icon: "🏃",
    theme: "--c-red",
    age: "3-6 岁",
    tag: "反应·躲避",
  },
  {
    id: "dance-step",
    title: "舞步",
    subtitle: "记住舞步顺序",
    icon: "💃",
    theme: "--c-purple",
    age: "4-6 岁",
    tag: "记忆·身体",
  },
  {
    id: "stretch-game",
    title: "伸展",
    subtitle: "跟着做伸展动作",
    icon: "🧘",
    theme: "--c-teal",
    age: "3-6 岁",
    tag: "认知·身体",
  },
  {
    id: "breath-game",
    title: "深呼吸",
    subtitle: "跟着节奏呼吸",
    icon: "🌬️",
    theme: "--c-cyan",
    age: "3-6 岁",
    tag: "认知·放松",
  },
  // —— 古诗 / 3-4 岁认知启蒙 / 大动作（内容补缺）——
  {
    id: "classical-poem",
    title: "学古诗",
    subtitle: "补全古诗的一句",
    icon: "📜",
    theme: "--c-yellow",
    age: "5-6 岁",
    tag: "语言·古诗",
  },
  {
    id: "big-small",
    title: "比大小",
    subtitle: "哪个更大或更小",
    icon: "🐘",
    theme: "--c-orange",
    age: "3-4 岁",
    tag: "认知·比较",
  },
  {
    id: "color-find",
    title: "找颜色",
    subtitle: "点出指定颜色的球",
    icon: "🎨",
    theme: "--c-red",
    age: "3-4 岁",
    tag: "认知·颜色",
  },
  {
    id: "shape-find",
    title: "找形状",
    subtitle: "点出指定的形状",
    icon: "⭐",
    theme: "--c-yellow",
    age: "3-4 岁",
    tag: "认知·图形",
  },
  {
    id: "count-finger",
    title: "手指数数",
    subtitle: "数手指 1 到 5",
    icon: "✋",
    theme: "--c-blue",
    age: "3-4 岁",
    tag: "数学·计数",
  },
  {
    id: "throw-ball",
    title: "投球练习",
    subtitle: "站起来投球入篓",
    icon: "🤾",
    theme: "--c-green",
    age: "3-6 岁",
    tag: "健康·投掷",
  },
  {
    id: "kick-ball",
    title: "踢球练习",
    subtitle: "用脚踢球出去",
    icon: "⚽",
    theme: "--c-green",
    age: "3-6 岁",
    tag: "健康·踢腿",
  },
  {
    id: "follow-action",
    title: "跟我做",
    subtitle: "跟着做大动作",
    icon: "🤸",
    theme: "--c-pink",
    age: "3-4 岁",
    tag: "健康·模仿",
  },
  // —— 内容补缺 5 个（唐诗/季节/安全/科学/货币）——
  {
    id: "tang-sanbai",
    title: "唐诗三百首",
    subtitle: "补全唐诗的一句",
    icon: "📜",
    theme: "--c-indigo",
    age: "5-6 岁",
    tag: "语言·古诗",
  },
  {
    id: "seasons-match",
    title: "四季配对",
    subtitle: "季节特征配对",
    icon: "🍂",
    theme: "--c-orange",
    age: "3-4 岁",
    tag: "认知·季节",
  },
  {
    id: "traffic-light",
    title: "过马路",
    subtitle: "看灯过马路",
    icon: "🚦",
    theme: "--c-red",
    age: "3-5 岁",
    tag: "生活·安全",
  },
  {
    id: "shadow-size",
    title: "影子比大小",
    subtitle: "比较不同时间的影子",
    icon: "🌤️",
    theme: "--c-yellow",
    age: "4-5 岁",
    tag: "科学·测量",
  },
  {
    id: "money-pay",
    title: "付钱练习",
    subtitle: "用硬币组合付够钱",
    icon: "💰",
    theme: "--c-green",
    age: "5-6 岁",
    tag: "数学·货币",
  },
  {
    id: "color-flash",
    title: "颜色快闪",
    subtitle: "记住颜色闪烁顺序，训练短期记忆",
    icon: "💡",
    theme: "--c-blue",
    age: "4-6 岁",
    tag: "记忆·顺序",
  },
  {
    id: "number-trace-2",
    title: "数字描红",
    subtitle: "1-20 数字书写练习，描虚线轮廓",
    icon: "✏️",
    theme: "--c-orange",
    age: "3-5 岁",
    tag: "数学·书写",
  },
  {
    id: "skip-count",
    title: "跳数填空",
    subtitle: "2/5/10 的倍数跳数序列",
    icon: "🔢",
    theme: "--c-green",
    age: "5-6 岁",
    tag: "数学·规律",
  },
  {
    id: "number-bond",
    title: "数字分解",
    subtitle: "一个数可以分成几和几",
    icon: "🧩",
    theme: "--c-purple",
    age: "4-6 岁",
    tag: "数学·组成",
  },
  {
    id: "number-line",
    title: "数轴找数",
    subtitle: "看箭头指向数轴上的哪个数",
    icon: "📏",
    theme: "--c-blue",
    age: "4-6 岁",
    tag: "数学·数轴",
  },
  {
    id: "missing-number",
    title: "填缺失数",
    subtitle: "连续数字缺一个，找出来",
    icon: "❓",
    theme: "--c-orange",
    age: "3-5 岁",
    tag: "数学·数序",
  },
  {
    id: "odd-even",
    title: "单数双数",
    subtitle: "判断数字是单数还是双数",
    icon: "🔀",
    theme: "--c-teal",
    age: "5-6 岁",
    tag: "数学·奇偶",
  },
  {
    id: "radical-build",
    title: "偏旁组字",
    subtitle: "偏旁加部件拼成真字",
    icon: "🔤",
    theme: "--c-indigo",
    age: "5-6 岁",
    tag: "语言·汉字",
  },
  {
    id: "picture-word",
    title: "看图认字",
    subtitle: "看图画选出对应汉字",
    icon: "🖼️",
    theme: "--c-orange",
    age: "3-5 岁",
    tag: "语言·识字",
  },
  {
    id: "word-pair",
    title: "词语配对",
    subtitle: "名词和相关词连起来",
    icon: "🔗",
    theme: "--c-pink",
    age: "4-6 岁",
    tag: "语言·词汇",
  },
  {
    id: "tone-game",
    title: "声调练习",
    subtitle: "辨认同音不同调的字",
    icon: "🎵",
    theme: "--c-purple",
    age: "5-6 岁",
    tag: "语言·语音",
  },
  {
    id: "char-structure",
    title: "汉字结构",
    subtitle: "认左右上下包围独体",
    icon: "🏗️",
    theme: "--c-blue",
    age: "5-6 岁",
    tag: "语言·汉字",
  },
  {
    id: "sentence-order",
    title: "句子排序",
    subtitle: "把词语排成完整句子",
    icon: "📖",
    theme: "--c-green",
    age: "5-6 岁",
    tag: "语言·阅读",
  },
  {
    id: "magnet-push",
    title: "磁铁推拉",
    subtitle: "拖磁铁吸铁珠，认识磁力",
    icon: "🧲",
    theme: "--c-purple",
    age: "4-6 岁",
    tag: "科学·磁力",
  },
  {
    id: "light-prism",
    title: "光的彩虹",
    subtitle: "白光过棱镜，排七色彩虹",
    icon: "🌈",
    theme: "--c-cyan",
    age: "4-6 岁",
    tag: "科学·光学",
  },
  {
    id: "sound-wave",
    title: "声音高低",
    subtitle: "听两个音，辨谁高谁低",
    icon: "🎵",
    theme: "--c-orange",
    age: "3-6 岁",
    tag: "科学·声学",
  },
  {
    id: "heat-flow",
    title: "热传导",
    subtitle: "判断哪种材质先变烫",
    icon: "🔥",
    theme: "--c-red",
    age: "5-6 岁",
    tag: "科学·热学",
  },
  {
    id: "state-change",
    title: "物态变化",
    subtitle: "冰水汽循环，融化排序",
    icon: "💧",
    theme: "--c-blue",
    age: "4-6 岁",
    tag: "科学·物态",
  },
  {
    id: "sink-float",
    title: "沉浮实验",
    subtitle: "猜猜物品放进水里沉还是浮",
    icon: "⛵",
    theme: "--c-teal",
    age: "3-5 岁",
    tag: "科学·浮力",
  },
  {
    id: "day-night-cycle",
    title: "昼夜变化",
    subtitle: "地球自转，认早晚与黑夜",
    icon: "🌍",
    theme: "--c-indigo",
    age: "3-5 岁",
    tag: "科学·天文",
  },
  {
    id: "soil-layers",
    title: "土壤层次",
    subtitle: "从上到下排地层，找化石蚯蚓",
    icon: "🌱",
    theme: "--c-brown",
    age: "5-6 岁",
    tag: "科学·地球",
  },
  // —— 趣味探索类 8 个（强调探索·发现·惊喜·创造）——
  {
    id: "mystery-box",
    title: "神秘盲盒",
    subtitle: "拆开盒子，看看里面是什么",
    icon: "🎁",
    theme: "--c-pink",
    age: "3-6 岁",
    tag: "认知·探索",
  },
  {
    id: "dino-dig",
    title: "考古挖掘",
    subtitle: "挖泥土找化石，拼出恐龙",
    icon: "🦴",
    theme: "--c-brown",
    age: "4-6 岁",
    tag: "科学·考古",
  },
  {
    id: "bubble-workshop",
    title: "泡泡工坊",
    subtitle: "吹泡泡戳泡泡，自由探索",
    icon: "🫧",
    theme: "--c-cyan",
    age: "3-6 岁",
    tag: "创造·探索",
  },
  {
    id: "scratch-card",
    title: "刮刮乐",
    subtitle: "刮开涂层，揭晓惊喜图案",
    icon: "🎴",
    theme: "--c-orange",
    age: "3-6 岁",
    tag: "认知·惊喜",
  },
  {
    id: "kaleidoscope",
    title: "万花筒",
    subtitle: "转动找对称的彩色图案",
    icon: "🔮",
    theme: "--c-purple",
    age: "3-5 岁",
    tag: "艺术·探索",
  },
  {
    id: "ocean-explore",
    title: "海底探险",
    subtitle: "翻海草，发现海洋生物",
    icon: "🐠",
    theme: "--c-blue",
    age: "4-6 岁",
    tag: "科学·探索",
  },
  {
    id: "color-lab",
    title: "色彩实验室",
    subtitle: "自由混色，调出目标色",
    icon: "🧪",
    theme: "--c-purple",
    age: "4-6 岁",
    tag: "科学·探索",
  },
  {
    id: "sound-garden",
    title: "声音花园",
    subtitle: "弹花朵奏旋律，自由探索",
    icon: "🎶",
    theme: "--c-green",
    age: "3-5 岁",
    tag: "艺术·探索",
  },
  {
    id: "schulte-grid",
    title: "舒尔特方格",
    subtitle: "按顺序点数字，专注力训练",
    icon: "🔢",
    theme: "--c-blue",
    age: "4-6 岁",
    tag: "专注·方格",
  },
  {
    id: "find-target",
    title: "找目标",
    subtitle: "在干扰中找目标，选择性注意力",
    icon: "🎯",
    theme: "--c-red",
    age: "3-6 岁",
    tag: "专注·搜索",
  },
  {
    id: "whack-mole-2",
    title: "打地鼠进阶",
    subtitle: "炸弹不能打，控制冲动反应抑制",
    icon: "🔨",
    theme: "--c-brown",
    age: "4-6 岁",
    tag: "专注·抑制",
  },
  {
    id: "listen-count",
    title: "听音数数",
    subtitle: "听叮声数几下，听觉注意力",
    icon: "👂",
    theme: "--c-purple",
    age: "4-6 岁",
    tag: "专注·听觉",
  },
  {
    id: "stroop-test",
    title: "色词干扰",
    subtitle: "看字的颜色不看意思，抗干扰",
    icon: "🎨",
    theme: "--c-pink",
    age: "5-6 岁",
    tag: "专注·干扰",
  },
  {
    id: "eye-trace",
    title: "视觉追踪",
    subtitle: "跟着弯曲线找终点，视觉追踪",
    icon: "🌀",
    theme: "--c-blue",
    age: "4-6 岁",
    tag: "专注·追踪",
  },
  {
    id: "sokoban",
    title: "推箱子",
    subtitle: "推动箱子到金色目标，只能推不能拉",
    icon: "📦",
    theme: "--c-brown",
    age: "5-6 岁",
    tag: "逻辑·推箱",
  },
  {
    id: "match-three",
    title: "宝石三消",
    subtitle: "交换相邻宝石凑同色连线消除",
    icon: "💎",
    theme: "--c-purple",
    age: "4-6 岁",
    tag: "逻辑·消除",
  },
  {
    id: "maze-builder",
    title: "迷宫建造",
    subtitle: "放墙引导小动物走到奶酪，反转迷宫",
    icon: "🏗️",
    theme: "--c-green",
    age: "4-6 岁",
    tag: "逻辑·建造",
  },
  {
    id: "word-puzzle",
    title: "汉字拼图",
    subtitle: "把部件拖回虚线格拼成完整汉字",
    icon: "🧩",
    theme: "--c-indigo",
    age: "5-6 岁",
    tag: "语言·拼字",
  },
  {
    id: "color-fill-2",
    title: "区域填色",
    subtitle: "每行每列颜色都不重复，进阶数独",
    icon: "🎨",
    theme: "--c-teal",
    age: "4-6 岁",
    tag: "逻辑·填色",
  },
  {
    id: "path-connect",
    title: "路径连通",
    subtitle: "把同色端点连起来，连线不能交叉",
    icon: "🔗",
    theme: "--c-blue",
    age: "4-6 岁",
    tag: "逻辑·连线",
  },
  {
    id: "task-switch",
    title: "任务切换",
    subtitle: "规则会变，灵活切换思维点对的",
    icon: "🔄",
    theme: "--c-indigo",
    age: "5-6 岁",
    tag: "认知·执行功能",
  },
  {
    id: "emotion-regulate",
    title: "情绪调节",
    subtitle: "遇到状况选好的应对方式",
    icon: "💗",
    theme: "--c-pink",
    age: "4-6 岁",
    tag: "社交·情绪",
  },
  {
    id: "cause-effect",
    title: "因果推理",
    subtitle: "由原因预测会发生什么",
    icon: "⚡",
    theme: "--c-yellow",
    age: "4-6 岁",
    tag: "科学·因果",
  },
  {
    id: "rhythm-tap",
    title: "节奏拍打",
    subtitle: "听鼓点模仿拍出节拍",
    icon: "🥁",
    theme: "--c-red",
    age: "3-5 岁",
    tag: "艺术·节奏",
  },
  {
    id: "story-create",
    title: "故事编创",
    subtitle: "排好顺序再讲出小故事",
    icon: "📖",
    theme: "--c-purple",
    age: "5-6 岁",
    tag: "语言·叙事",
  },
  {
    id: "spatial-memory",
    title: "空间记忆",
    subtitle: "记住亮过位置的格子",
    icon: "🗺️",
    theme: "--c-green",
    age: "4-6 岁",
    tag: "记忆·空间",
  },
] as const;

/** id → 元信息 的索引，避免 findGame 在热路径（每通关一次触发成就检测）线性扫描全部游戏。 */
const GAME_MAP: ReadonlyMap<string, GameMeta> = new Map(
  GAMES.map((g) => [g.id, g] as const),
);

/** 根据 id 查找元信息（O(1)）。 */
export function findGame(id: string): GameMeta | undefined {
  return GAME_MAP.get(id);
}

export const GAME_IDS: readonly GameId[] = GAMES.map((g) => g.id);
