/**
 * 游戏注册表 —— 81 个游戏的元信息（大厅卡片 + 路由用）。
 *
 * 顺序即大厅展示顺序。这里是产品内容规模的唯一事实来源：
 * README、存档、成就、家长面板等统计都应从 GAMES/GAME_IDS 推导。
 * 颜色主题对应 style.css 的 CSS 变量。
 */
import type { GameId, GameMeta } from "../types.ts";

export const GAMES: readonly GameMeta[] = [
  {
    id: "color-mixer",
    title: "色彩调配师",
    subtitle: "认识三原色，颜料真混合",
    icon: "🎨",
    theme: "--c-pink",
    age: "3-6 岁",
    tag: "认知·颜色",
  },
  {
    id: "shape-match",
    title: "形状配对",
    subtitle: "认识几何形状，配对小动物",
    icon: "🧩",
    theme: "--c-blue",
    age: "3-5 岁",
    tag: "认知·图形",
  },
  {
    id: "number-monster",
    title: "数字小怪兽",
    subtitle: "数数 1-20，喂饱小怪兽",
    icon: "🔢",
    theme: "--c-green",
    age: "4-6 岁",
    tag: "数学·计数",
  },
  {
    id: "letter-bee",
    title: "蜜蜂找字母",
    subtitle: "认字母首音，采对应花朵",
    icon: "🐝",
    theme: "--c-yellow",
    age: "4-6 岁",
    tag: "语言·字母",
  },
  {
    id: "memory-flip",
    title: "记忆翻翻乐",
    subtitle: "训练短时记忆，难度递增",
    icon: "🧠",
    theme: "--c-purple",
    age: "3-6 岁",
    tag: "逻辑·记忆",
  },
  {
    id: "music-stairs",
    title: "音乐楼梯",
    subtitle: "听音高节奏，弹奏小旋律",
    icon: "🎼",
    theme: "--c-orange",
    age: "3-6 岁",
    tag: "艺术·听觉",
  },
  {
    id: "maze-adventure",
    title: "走迷宫",
    subtitle: "空间推理，收集星星",
    icon: "🚗",
    theme: "--c-teal",
    age: "4-6 岁",
    tag: "逻辑·规划",
  },
  {
    id: "seek-find",
    title: "找一找",
    subtitle: "专注观察，发现隐藏物品",
    icon: "🎡",
    theme: "--c-red",
    age: "3-6 岁",
    tag: "专注·观察",
  },
  // ====== 第二批 16 个 ======
  {
    id: "size-sort",
    title: "大小排队",
    subtitle: "比较大小，从小到大排队",
    icon: "📏",
    theme: "--c-orange",
    age: "3-5 岁",
    tag: "认知·比较",
  },
  {
    id: "jigsaw",
    title: "拼图小能手",
    subtitle: "还原打乱的图片",
    icon: "🧩",
    theme: "--c-purple",
    age: "3-6 岁",
    tag: "认知·空间",
  },
  {
    id: "pattern",
    title: "找规律",
    subtitle: "发现重复序列的下一个",
    icon: "🔁",
    theme: "--c-blue",
    age: "4-6 岁",
    tag: "逻辑·推理",
  },
  {
    id: "whack-mole",
    title: "打地鼠",
    subtitle: "快速反应，锻炼手眼协调",
    icon: "🔨",
    theme: "--c-brown",
    age: "3-6 岁",
    tag: "反应·协调",
  },
  {
    id: "doodle",
    title: "涂鸦画板",
    subtitle: "自由绘画，换颜色画笔",
    icon: "🖌️",
    theme: "--c-pink",
    age: "3-6 岁",
    tag: "创造·艺术",
  },
  {
    id: "weather",
    title: "天气小助手",
    subtitle: "认识天气与穿衣",
    icon: "🌤️",
    theme: "--c-teal",
    age: "3-6 岁",
    tag: "认知·生活",
  },
  {
    id: "clock",
    title: "小小时钟",
    subtitle: "认识整点与半点",
    icon: "🕐",
    theme: "--c-yellow",
    age: "5-6 岁",
    tag: "认知·时间",
  },
  {
    id: "animal-sound",
    title: "谁的声音",
    subtitle: "听声音猜动物",
    icon: "🐮",
    theme: "--c-green",
    age: "3-6 岁",
    tag: "认知·听觉",
  },
  {
    id: "color-sort",
    title: "颜色分家",
    subtitle: "按颜色把物品分类",
    icon: "🗂️",
    theme: "--c-cyan",
    age: "3-5 岁",
    tag: "认知·分类",
  },
  {
    id: "connect-dots",
    title: "连点成画",
    subtitle: "按数字顺序连线出图",
    icon: "✏️",
    theme: "--c-orange",
    age: "4-6 岁",
    tag: "认知·数序",
  },
  {
    id: "shadow-match",
    title: "影子朋友",
    subtitle: "把物品和它的影子配对",
    icon: "👥",
    theme: "--c-indigo",
    age: "3-6 岁",
    tag: "认知·观察",
  },
  {
    id: "tangram",
    title: "七巧板",
    subtitle: "用形状拼出图案",
    icon: "🔷",
    theme: "--c-purple",
    age: "4-6 岁",
    tag: "创造·空间",
  },
  {
    id: "farm-math",
    title: "小农场算术",
    subtitle: "数动物做加减法",
    icon: "🐔",
    theme: "--c-green",
    age: "5-6 岁",
    tag: "数学·运算",
  },
  {
    id: "balance",
    title: "天平称重",
    subtitle: "比较轻重，让天平平衡",
    icon: "⚖️",
    theme: "--c-teal",
    age: "4-6 岁",
    tag: "认知·比较",
  },
  {
    id: "robot-code",
    title: "小指令机器人",
    subtitle: "排指令让机器人到达终点",
    icon: "🤖",
    theme: "--c-blue",
    age: "5-6 岁",
    tag: "逻辑·编程",
  },
  {
    id: "dress-up",
    title: "换装搭配",
    subtitle: "给角色搭配服装",
    icon: "👕",
    theme: "--c-pink",
    age: "3-6 岁",
    tag: "创造·生活",
  },
  // ====== 第三批 25 个 ======
  {
    id: "fruit-catch",
    title: "接水果",
    subtitle: "移动篮子接水果",
    icon: "🧺",
    theme: "--c-green",
    age: "3-6 岁",
    tag: "反应·协调",
  },
  {
    id: "link-match",
    title: "连连看",
    subtitle: "相同图案连线消除",
    icon: "🔗",
    theme: "--c-cyan",
    age: "4-6 岁",
    tag: "观察·配对",
  },
  {
    id: "feed-order",
    title: "喂养顺序",
    subtitle: "按指定顺序点动物",
    icon: "🍖",
    theme: "--c-orange",
    age: "3-6 岁",
    tag: "记忆·顺序",
  },
  {
    id: "pinyin",
    title: "拼音首字母",
    subtitle: "找对应拼音的字",
    icon: "🔤",
    theme: "--c-blue",
    age: "5-6 岁",
    tag: "语言·拼音",
  },
  {
    id: "antonym",
    title: "找反义词",
    subtitle: "把意思相反的词配对",
    icon: "⚖️",
    theme: "--c-indigo",
    age: "5-6 岁",
    tag: "语言·词汇",
  },
  {
    id: "sliding-puzzle",
    title: "数字华容道",
    subtitle: "滑动方块排顺序",
    icon: "🔢",
    theme: "--c-purple",
    age: "4-6 岁",
    tag: "逻辑·策略",
  },
  {
    id: "color-reaction",
    title: "颜色反应",
    subtitle: "听颜色名点对应色",
    icon: "🌈",
    theme: "--c-pink",
    age: "3-6 岁",
    tag: "反应·认知",
  },
  {
    id: "equation",
    title: "等式填空",
    subtitle: "填数字让等式成立",
    icon: "➗",
    theme: "--c-teal",
    age: "5-6 岁",
    tag: "数学·运算",
  },
  {
    id: "spot-diff",
    title: "找不同",
    subtitle: "找出两图的不同",
    icon: "🔍",
    theme: "--c-red",
    age: "4-6 岁",
    tag: "专注·观察",
  },
  {
    id: "tidy-up",
    title: "收拾房间",
    subtitle: "把物品放回原位",
    icon: "🧹",
    theme: "--c-brown",
    age: "3-6 岁",
    tag: "生活·分类",
  },
  {
    id: "mini-sudoku",
    title: "迷你数独",
    subtitle: "填不重复的图案",
    icon: "🔲",
    theme: "--c-indigo",
    age: "5-6 岁",
    tag: "逻辑·推理",
  },
  {
    id: "pipe-connect",
    title: "接水管",
    subtitle: "旋转管道连通水流",
    icon: "🚰",
    theme: "--c-cyan",
    age: "4-6 岁",
    tag: "逻辑·空间",
  },
  {
    id: "weight-sort",
    title: "称重排序",
    subtitle: "按轻重给动物排队",
    icon: "🐘",
    theme: "--c-brown",
    age: "4-6 岁",
    tag: "认知·比较",
  },
  {
    id: "catch-star",
    title: "接星星",
    subtitle: "限时收集掉落星星",
    icon: "⭐",
    theme: "--c-yellow",
    age: "3-6 岁",
    tag: "反应·协调",
  },
  {
    id: "draw-along",
    title: "照着画",
    subtitle: "沿虚线临摹图形",
    icon: "✒️",
    theme: "--c-purple",
    age: "3-6 岁",
    tag: "创造·精细",
  },
  {
    id: "emotion",
    title: "表情配对",
    subtitle: "情境配上对应情绪",
    icon: "😀",
    theme: "--c-orange",
    age: "3-6 岁",
    tag: "社交·情商",
  },
  {
    id: "direction",
    title: "方向辨别",
    subtitle: "分清左右上下",
    icon: "🧭",
    theme: "--c-blue",
    age: "4-6 岁",
    tag: "认知·空间",
  },
  {
    id: "length",
    title: "比长短",
    subtitle: "比较物品的长短",
    icon: "📏",
    theme: "--c-teal",
    age: "3-5 岁",
    tag: "认知·比较",
  },
  {
    id: "more-less",
    title: "多少比较",
    subtitle: "比较两组数量多少",
    icon: "⚖️",
    theme: "--c-green",
    age: "3-5 岁",
    tag: "数学·比较",
  },
  {
    id: "symmetry",
    title: "对称补全",
    subtitle: "补全对称的另一半",
    icon: "🦋",
    theme: "--c-pink",
    age: "4-6 岁",
    tag: "认知·空间",
  },
  {
    id: "rhythm",
    title: "节奏模仿",
    subtitle: "记忆并重复鼓点",
    icon: "🥁",
    theme: "--c-red",
    age: "3-6 岁",
    tag: "艺术·听觉",
  },
  {
    id: "fishing",
    title: "钓鱼",
    subtitle: "钓起指定的鱼",
    icon: "🎣",
    theme: "--c-cyan",
    age: "3-6 岁",
    tag: "反应·观察",
  },
  {
    id: "block-tower",
    title: "搭积木",
    subtitle: "把积木叠得又高又稳",
    icon: "🧱",
    theme: "--c-orange",
    age: "3-6 岁",
    tag: "精细·平衡",
  },
  {
    id: "word-chain",
    title: "词语接龙",
    subtitle: "首尾相接排词语",
    icon: "🔠",
    theme: "--c-purple",
    age: "5-6 岁",
    tag: "语言·词汇",
  },
  {
    id: "reverse-memory",
    title: "倒序记忆",
    subtitle: "记住后倒着点出来",
    icon: "🔄",
    theme: "--c-indigo",
    age: "5-6 岁",
    tag: "记忆·逆向",
  },
  // ====== 第四批 32 个 ======
  {
    id: "claw",
    title: "抓娃娃机",
    subtitle: "抓准时机抓起玩偶",
    icon: "🧸",
    theme: "--c-pink",
    age: "3-6 岁",
    tag: "反应·时机",
  },
  {
    id: "bubble-shoot",
    title: "泡泡射击",
    subtitle: "瞄准发射消除同色",
    icon: "🫧",
    theme: "--c-cyan",
    age: "4-6 岁",
    tag: "瞄准·策略",
  },
  {
    id: "wheel",
    title: "幸运转盘",
    subtitle: "转盘停在哪个颜色",
    icon: "🎡",
    theme: "--c-orange",
    age: "3-6 岁",
    tag: "概率·反应",
  },
  {
    id: "pinball",
    title: "弹珠台",
    subtitle: "弹珠撞击得分",
    icon: "🔮",
    theme: "--c-purple",
    age: "4-6 岁",
    tag: "物理·弹射",
  },
  {
    id: "guess-card",
    title: "猜大小",
    subtitle: "翻牌猜下一张大或小",
    icon: "🃏",
    theme: "--c-red",
    age: "4-6 岁",
    tag: "概率·推理",
  },
  {
    id: "snake",
    title: "贪吃蛇",
    subtitle: "控制蛇吃食物变长",
    icon: "🐍",
    theme: "--c-green",
    age: "4-6 岁",
    tag: "控制·反应",
  },
  {
    id: "2048",
    title: "数字合并",
    subtitle: "滑动合并相同数字",
    icon: "🔢",
    theme: "--c-blue",
    age: "5-6 岁",
    tag: "策略·数字",
  },
  {
    id: "number-sequence",
    title: "数字序列",
    subtitle: "补全数列缺的数字",
    icon: "🔗",
    theme: "--c-teal",
    age: "5-6 岁",
    tag: "数学·规律",
  },
  {
    id: "pinyin-puzzle",
    title: "拼音拼图",
    subtitle: "把声母韵母拼成音节",
    icon: "🔤",
    theme: "--c-blue",
    age: "5-6 岁",
    tag: "语言·拼音",
  },
  {
    id: "radical",
    title: "部首配对",
    subtitle: "给部首找对应的字",
    icon: "🧩",
    theme: "--c-indigo",
    age: "5-6 岁",
    tag: "语言·汉字",
  },
  {
    id: "idiom",
    title: "成语填字",
    subtitle: "补全成语缺的字",
    icon: "📜",
    theme: "--c-purple",
    age: "5-6 岁",
    tag: "语言·成语",
  },
  {
    id: "measure-word",
    title: "量词搭配",
    subtitle: "一只、一条、一个",
    icon: "📏",
    theme: "--c-green",
    age: "4-6 岁",
    tag: "语言·量词",
  },
  {
    id: "stroke-order",
    title: "笔画顺序",
    subtitle: "按正确笔顺写字",
    icon: "✍️",
    theme: "--c-brown",
    age: "5-6 岁",
    tag: "语言·书写",
  },
  {
    id: "homophone",
    title: "同音字",
    subtitle: "辨析读音相同的字",
    icon: "🔊",
    theme: "--c-yellow",
    age: "5-6 岁",
    tag: "语言·辨析",
  },
  {
    id: "similar-char",
    title: "形近字",
    subtitle: "辨析长得很像的字",
    icon: "👀",
    theme: "--c-cyan",
    age: "5-6 岁",
    tag: "语言·辨析",
  },
  {
    id: "word-classify",
    title: "词语分类",
    subtitle: "把词语归到正确类别",
    icon: "🗂️",
    theme: "--c-teal",
    age: "4-6 岁",
    tag: "语言·分类",
  },
  {
    id: "fraction",
    title: "分数披萨",
    subtitle: "切披萨认识分数",
    icon: "🍕",
    theme: "--c-red",
    age: "5-6 岁",
    tag: "数学·分数",
  },
  {
    id: "time-timeline",
    title: "时间线",
    subtitle: "把事件按时间排序",
    icon: "⏳",
    theme: "--c-orange",
    age: "4-6 岁",
    tag: "认知·时间",
  },
  {
    id: "thermometer",
    title: "温度计",
    subtitle: "读取温度认识冷热",
    icon: "🌡️",
    theme: "--c-red",
    age: "4-6 岁",
    tag: "认知·测量",
  },
  {
    id: "calendar",
    title: "日历认知",
    subtitle: "认识星期和日期",
    icon: "📅",
    theme: "--c-blue",
    age: "5-6 岁",
    tag: "认知·日期",
  },
  {
    id: "money",
    title: "小小钱包",
    subtitle: "认识人民币换算",
    icon: "💰",
    theme: "--c-green",
    age: "5-6 岁",
    tag: "数学·货币",
  },
  {
    id: "ruler",
    title: "测量尺",
    subtitle: "用尺子量物品长度",
    icon: "📐",
    theme: "--c-teal",
    age: "4-6 岁",
    tag: "认知·测量",
  },
  {
    id: "symmetry-axis",
    title: "对称轴",
    subtitle: "判断图形的对称轴",
    icon: "✿",
    theme: "--c-pink",
    age: "5-6 岁",
    tag: "认知·几何",
  },
  {
    id: "3d-shape",
    title: "立体图形",
    subtitle: "认识立方体球体圆柱",
    icon: "🎲",
    theme: "--c-purple",
    age: "4-6 岁",
    tag: "认知·立体",
  },
  {
    id: "color-gradient",
    title: "颜色渐变",
    subtitle: "把颜色按深浅排序",
    icon: "🌈",
    theme: "--c-pink",
    age: "3-6 岁",
    tag: "认知·色彩",
  },
  {
    id: "spectrum",
    title: "光谱排序",
    subtitle: "按彩虹顺序排列颜色",
    icon: "🌠",
    theme: "--c-indigo",
    age: "4-6 岁",
    tag: "认知·科学",
  },
  {
    id: "constellation",
    title: "星座连线",
    subtitle: "连线画出星座图案",
    icon: "⭐",
    theme: "--c-indigo",
    age: "4-6 岁",
    tag: "科学·天文",
  },
  {
    id: "planet-orbit",
    title: "行星轨道",
    subtitle: "认识太阳系行星",
    icon: "🪐",
    theme: "--c-purple",
    age: "4-6 岁",
    tag: "科学·天文",
  },
  {
    id: "ecosystem",
    title: "食物链",
    subtitle: "排出谁吃谁的关系",
    icon: "🦊",
    theme: "--c-green",
    age: "5-6 岁",
    tag: "科学·生物",
  },
  {
    id: "weather-forecast",
    title: "天气预测",
    subtitle: "根据线索预测天气",
    icon: "⛈️",
    theme: "--c-cyan",
    age: "5-6 岁",
    tag: "科学·气象",
  },
  {
    id: "magnet-maze",
    title: "磁铁迷宫",
    subtitle: "磁力引导小球到终点",
    icon: "🧲",
    theme: "--c-red",
    age: "4-6 岁",
    tag: "科学·磁力",
  },
  {
    id: "circuit",
    title: "电路连通",
    subtitle: "连接电路让灯泡亮起",
    icon: "💡",
    theme: "--c-yellow",
    age: "5-6 岁",
    tag: "科学·电学",
  },
] as const;

/** 根据 id 查找元信息。 */
export function findGame(id: string): GameMeta | undefined {
  return GAMES.find((g) => g.id === id);
}

export const GAME_IDS: readonly GameId[] = GAMES.map((g) => g.id);
